{
  "hash": "89a485cf1da5e3bc79b65b980e396550",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Among U.S. children aged 0–17, is low birth weight associated with increased odds of an ever asthma diagnosis, after adjusting for child age, sex, race/ethnicity, household income, and secondhand smoke exposure?\"\nauthor:\n  - name: Javier Diaz Collante\n    email: jdiazcollant@umass.edu\n  - name: Rachel Huselid,\n    email: rhuselid@schoolph.umass.edu,\n  - name: Anjelica Martinez\n    email: anjelicamart@umass.edu\n    affiliation: Department of Biostatistics & Epidemiology\n  - name: \"Created on: June 28, 2026\"\nauthor-title: \"Author\"\naffiliation-title: \"University of Massachusetts - Amherst\"\nabstract-title: Purpose\nabstract: This notebook is for the analysis portion of our EPI 690A final project.\npublished-title: \"Date Updated\"\nformat:\n  html:\n    embed-resources: true\n    anchor-sections: true\n    code-fold: show\n    code-tools: true\n    fig-width: 6\n    fig-height: 4\n    code-block-bg: \"#f1f3f5\"\n    code-block-border-left: \"#31BAE9\"\n    mainfont: Source Sans Pro\n    theme: journal\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    captions: true\n    table-captions: true\n---\n\n# Introduction\n\nAsthma is one of the most common chronic diseases of childhood in the United States and is a leading cause of emergency department visits, hospitalizations, missed school days, and reduced quality of life in children. Although genetic predisposition contributes to asthma risk, early-life factors have also been recognized as important determinants of many chronic diseases. Low birth weight, often resulting from preterm birth or other factors, has been associated with underdeveloped lung development and increased susceptibility to respiratory disease later in childhood. However, because childhood asthma is also influenced by demographic, socioeconomic, and environmental factors, it is important to evaluate whether the relationship between low birth weight and asthma persists after accounting for these potential confounders.\n\nUsing data from the 2023 [National Survey of Children's Health (NSCH)](https://mchb.hrsa.gov/data-research/national-survey-childrens-health) a nationally representative cross-sectional survey of U.S. children aged 0–17 years, this project will examine whether low birth weight is associated with the likelihood of ever receiving an asthma diagnosis. Specifically, the research question is: among U.S. children aged 0–17 years, is low birth weight associated with increased odds of ever having an asthma diagnosis after adjusting for age, sex, race, household income, and secondhand smoke exposure? We hypothesize that children with a history of low birth weight will have a higher likelihood of ever being diagnosed with asthma compared with children of normal birth weight, even after controlling for these possible confounders.\n\n# Methods\n\n## Study population\n\nThe [2023 National Survey of Children's Health (NSCH)](www2.census.gov/programs-surveys/nsch/technical-documentation/methodology/2023-NSCH-Methodology-Report.pdf) survey population focused on non-institutionalized children in the United States ages 0–17. The sample size nationally was 55,162 children, and the state sample size ranged from 710 to 4,696 children. Participants were randomly sampled by household and contacted by mail directly to determine whether the household had one or more children under the age of 18. If the household was determined to have more than one child, one child was chosen at random to be the subject of the survey. Children with special health care needs and children between the ages of 0 and 5 were oversampled in the survey. A total of nine states and one metropolitan area (California, Colorado, Nebraska, New York, Ohio, Oregon, Pennsylvania, Tennessee, Wisconsin, and Atlanta, Georgia) provided oversampling funding to support additional interviews and allow reporting for specific population groups, conditions, or localities in these locations. The survey data were weighted to represent the population of non-institutionalized children between the ages of 0 and 17 both nationally and by state. The overall weighted response rate of the survey was 35.8%.\n\nThe survey data were collected via online forms or a physical paper version. Each household was mailed an invitation in which the adult of the house familiar with the child's health and health care was asked to complete a short screener questionnaire (via web or paper). The questionnaire asked participants to identify whether there were children in the household between the ages of 0 and 17 and to report their ages. If a child was in the home and the participant wished to complete the survey online, they were directed to a link with more detailed age-specific questions for the one randomly selected child. The survey was provided in both English and Spanish. Participants also had the option to use telephone assistance.\n\n## Exposure\n\nThe primary exposure was birth weight status, defined using the variable `BIRTHWT_L`, which classifies children as having low birth weight (less than 2,500 grams) or normal birth weight. Low birth weight was treated as a binary variable, with normal birth weight as the reference group. This variable is provided as a pre-derived field in the NSCH public use file and required no additional recoding. \n\n## Outcome\n\nThe primary outcome was ever having received an asthma diagnosis, defined using the variable `K2Q40A`, which asks whether a doctor or other health care provider has ever told the respondent that the child has asthma. This was treated as a binary outcome, with children never diagnosed with asthma serving as the reference group. We initially considered distinguishing children with current versus previous asthma diagnoses using the companion variable `K2Q40B`, but ultimately used the single binary ever asthma variable for all descriptive and modeling purposes, since it captures any lifetime occurrence of the diagnosis and avoids ambiguity in how to classify children whose asthma has resolved.\n\n## Covariates\n\nCovariates were selected based on their established or plausible relationship to both birth weight and childhood asthma risk, and on the completeness of their measurement across the full 0 to 17 age range. The fully adjusted model included child age, sex, race, preterm birth status, familial poverty ratio, highest level of parental education, and insurance type. Age was included in the overall adjusted model but was excluded from the covariate set in age stratified analyses, since age itself defines the stratification.\n\nSecondhand smoke exposure, vaping exposure inside the home, and allergy history were described in the study population but were not included in the adjusted model. These variables were treated separately because our adjustment strategy prioritized demographic and socioeconomic covariates with minimal missingness, and because including additional covariates would have further reduced the analytic sample available for the fully adjusted model. Body mass index category was considered but excluded from all models, since this measure is only collected for children ages 6 to 17 and is therefore missing for the majority of younger children in the sample. In addition, because body mass index is measured cross sectionally at the time of the survey, it cannot be used to establish whether excess weight preceded or followed an asthma diagnosis.\n\n## Statistical Methods\n\nWithin this population, our analytic sample was further restricted to children with non-missing responses for the primary exposure and outcome variables, since these two variables define the research question. A flow diagram will report the sample size at each stage of this restriction, from the total NSCH respondent pool through the final analytic sample, along with the number of children excluded at each step. Missing covariate data was not used to exclude children from the overall analytic sample or from unadjusted analyses; rather, covariate missingness was allowed to reduce the sample size only within models that included the affected covariate. \n\nWe retained the full pediatric age range of 0 to 17 years for our primary analysis, since restricting the sample by age would have limited the birth weight information available for the youngest children, who are closest in time to their birth history. However, because asthma diagnoses accumulate over childhood and younger children have had less opportunity to be diagnosed, we conducted a parallel analysis stratified by age group to evaluate whether the association between birth weight and asthma differed across developmental stages.\n\nDescriptive statistics were generated for the exposure, outcome, and all covariates, stratified by asthma status, with means and standard deviations reported for continuous variables and frequencies and percentages reported for categorical variables. Bivariate comparisons between birth weight status and childhood characteristics were assessed using chi-square tests for categorical variables.\n\nThe association between birth weight status and ever having an asthma diagnosis was estimated using logistic regression, and results are presented as both prevalence differences and odds ratios with accompanying 95% confidence intervals, since absolute and relative measures each provide distinct and clinically relevant information. Prevalence differences were estimated as average marginal effects, averaging the difference in predicted asthma probability across all observations in the sample. We used this approach rather than evaluating the contrast at a single representative covariate profile, which yields wider standard errors and is more sensitive to the choice of profile values. Models were built in a staged sequence to account for the effect of missing covariate data on sample size. The first model was unadjusted. The second model adjusted for child age alone, since age was fully observed and allowed us to assess confounding by age before introducing covariates with missing values. The third model was fully adjusted for sex, race, preterm birth, familial poverty ratio, parental education, household smoker status, and insurance type. The analytic sample size is reported for each stage of this sequence.\n\nFinally, the fully adjusted model was repeated separately within four age strata, infants and toddlers (0 to 2 years), preschool age (3 to 5 years), middle childhood (6 to 12 years), and adolescents (13 to 17 years), to evaluate whether the association between birth weight and asthma diagnosis was consistent across childhood or concentrated within a particular developmental period.\n\n------------------------------------------------------------------------\n\n# Codebook\n\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n|                        |                             |                                                            |                                                                                                          |\n+========================+=============================+============================================================+==========================================================================================================+\n| **New Variable**       | **Original Variable**       | **Label**                                                  | **Values**                                                                                               |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `age`                  | `SC_AGE_YEARS`              | Age of selected child (years)                              |                                                                                                          |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `sex`                  | `SC_SEX`                    | Sex of selected child                                      | 1 = Male\\                                                                                                |\n|                        |                             |                                                            | 2 = Female                                                                                               |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `race`                 | `SC_RACE_R`                 | Race of selected child                                     | 1 = White alone\\                                                                                         |\n|                        |                             |                                                            | 2 = Black or African American alone\\                                                                     |\n|                        |                             |                                                            | 3 = American Indian or Alaska Native alone\\                                                              |\n|                        |                             |                                                            | 4 = Asian alone\\                                                                                         |\n|                        |                             |                                                            | 5 = Native Hawaiian and Other Pacific Islander alone\\                                                    |\n|                        |                             |                                                            | 7 = Two or More Races                                                                                    |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `hispanic`             | `SC_HISPANIC_R`             | Hispanic or Latino origin of selected child                | 1 = Yes\\                                                                                                 |\n|                        |                             |                                                            | 2 = No                                                                                                   |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `birth_weight_status`  | `BIRTHWT`                   | Birth weight status                                        | 1 = Very low birth weight (less than 1,500g)\\                                                            |\n|                        |                             |                                                            | 2 = Low birth weight (less than 2,500g)\\                                                                 |\n|                        |                             |                                                            | 3 = Not low birth weight                                                                                 |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `birth_weight_ver_low` | `BIRTHWT_VL`                | Birth weight is very low (\\<1500g)                         | 1 = Yes\\                                                                                                 |\n|                        |                             |                                                            | 2 = No                                                                                                   |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `birth_weight_low`     | `BIRTHWT_L`                 | Birth weight is low (\\<2500g)                              | 1 = Yes\\                                                                                                 |\n|                        |                             |                                                            | 2 = No                                                                                                   |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `asthma`               | `K2Q40A`                    | Ever diagnosed with asthma                                 | 1 = Yes\\                                                                                                 |\n|                        |                             |                                                            | 2 = No                                                                                                   |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `born_early`           | `K2Q05`                     | Born 3 or more weeks before due date                       | 1 = Yes\\                                                                                                 |\n|                        |                             |                                                            | 2 = No                                                                                                   |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `poverty`              | `FPL_I1`                    | Family poverty ratio, first implicate                      | 50 or less - 400 or more                                                                                 |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `education`            | `HIGRADE_TVIS`              | Highest level of education among reported adults, Detailed | 1 = Less than high school\\                                                                               |\n|                        |                             |                                                            | 2 = High school (including vocational, trade, or business school)\\                                       |\n|                        |                             |                                                            | 3 = Some college or Associate Degree\\                                                                    |\n|                        |                             |                                                            | 4 = College degree or higher                                                                             |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `insurance_type`       | `INSTYPE`                   | Insurance type                                             | 1 = Public only (government assistance)\\                                                                 |\n|                        |                             |                                                            | 2 = Private only (privately purchased, including through ACA marketplace, through employer, or TRICARE)\\ |\n|                        |                             |                                                            | 3 = Private and public\\                                                                                  |\n|                        |                             |                                                            | 5 = Not insured                                                                                          |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `cigarettes`           | `K9Q40`                     | Anyone in household use cigarettes                         | 1 = Yes\\                                                                                                 |\n|                        |                             |                                                            | 2 = No                                                                                                   |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `vape`                 | `VAPE`                      | Vape/E-Cigarettes inside of home                           | 1 = Yes\\                                                                                                 |\n|                        |                             |                                                            | 2 = No                                                                                                   |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `allergies`            | `ALLERGIES`                 | Ever diagnosed with allergies                              | 1 = Yes\\                                                                                                 |\n|                        |                             |                                                            | 2 = No                                                                                                   |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| `age_cats`\\*           | Created from `age` variable | Age group                                                  | Infants/Toddlers (0-2)\\                                                                                  |\n|                        |                             |                                                            | Preschool (3-5)\\                                                                                         |\n|                        |                             |                                                            | Middle childhood (6-12)\\                                                                                 |\n|                        |                             |                                                            | Teenagers (13-17)                                                                                        |\n+------------------------+-----------------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n\n~Codebook provided by the 2023 National Survey of Children's Health (NSCH)~\\\n~\\*This variable were created in 01_epi690a_final_project_DM.qmd~\n\n------------------------------------------------------------------------\n\n# Setup\n\nLoad relevant packages and setup code to help with HTML rendering.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Packages\"}\n# Packages Used\npacman::p_load(\n    dplyr,          # data manipulation\n    forcats,        # tools for working with categorical variables\n    here,           # file paths relative to R project root folder\n    rio,            # import/export of many types of data \n    tidyverse,      # includes many packages for tidy data wrangling \n    Hmisc,          # includes many functions in Harrellverse \n    data.table,     # (alternative) faster than tidyverse\n    qreport,        # useful for formatting in quarto\n    sparkline,      # inline interactive plots\n    lubridate,      # simplifies working with dates\n    janitor,        # tables and data cleaning\n    skimr,          # summary statistics\n    gtsummary,      # making descriptive and statistical tables\n    rstatix,        # quickly run statistical tests and summaries\n    labelled,       # labels variables\n    naniar,         # assessing missing data\n    datadictionary, # creates data dictionaries\n    haven,          # read/handle labelled data (e.g. SPSS/Stata/SAS files)\n    marginaleffects, # predictions, comparisons, and hypothesis tests\n    modelsummary,\n    broom,\n    stringr,\n    gt,\n    tibble\n )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Setup\"}\n# Source: Frank Harrell https://hbiostat.org/rflow/ \n# Make base graphics look better:\nspar <- function(bot=0, left=0, top=0, rt=0)\n  par(mar=c(3.25 + bot, 5 + left, 0.5 + top, 0.5 * rt),\n      lwd=1.75, mgp=c(2.0, 0.475, 0), tcl=-0.4, xpd=FALSE, ps=14,\n      cex.lab=1.15, cex.axis=0.8)\n\n# Set abbreviations for chunk option names\nknitr::set_alias(w = 'fig.width', h = 'fig.height')\n\noptions(prType='html')   # for certain Hmisc and rms functions\n\n# To automatically sense which output format is being created and \n# create a character string that will work for both `html` and `LaTeX`.  \n# For `LaTeX`, a boxed note in the body of the document will appear.\n\nishtml <- knitr::is_html_output()\nmNote  <- if(ishtml) '.column-margin' else '.callout-note appearance=\"minimal\"'\n\n#FHarrell: \"Note that to initialize javascript jQuery dependencies \n# we must include sparkline::sparkline(0) somewhere in the report \n# before creating the first sparkline output.\"\nsparkline::sparkline(0)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<span id=\"htmlwidget-745888cefff37b1c44c3\" class=\"sparkline html-widget\"></span>\n<script type=\"application/json\" data-for=\"htmlwidget-745888cefff37b1c44c3\">{\"x\":{\"values\":0,\"options\":{\"height\":20,\"width\":60},\"width\":60,\"height\":20},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n# Load Data\n\nData was collected from the canvas website and originally created by the National Survey of Children's Health (NSCH). The data were cleaned and prepared in the data management notebook `01_epi690a_final_project_DM.qmd` (and the resulting processed dataset `nsch2023_processed.rdata` is loaded below.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Load Data\"}\n# Import data\ndf <- import(here(\"data\", \"processed\", \"nsch2023_processed.rdata\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Missing `trust` will be set to FALSE by default for RData in 2.0.0.\n```\n\n\n:::\n\n```{.r .cell-code  code-summary=\"Load Data\"}\n# Review data structure\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  age                age_cats    sex                      race hispanic\n1  11 Middle childhood (6-12)   Male Black or African American       No\n2  14       Teenagers (13-17) Female                     White      Yes\n3  17       Teenagers (13-17) Female                     White      Yes\n4  12 Middle childhood (6-12) Female                     White      Yes\n5  10 Middle childhood (6-12) Female                     Asian       No\n6  14       Teenagers (13-17) Female                     White      Yes\n   birth_weight_status birth_weight_very_low birth_weight_low asthma born_early\n1 Not low birth weight                    No               No    Yes         No\n2 Not low birth weight                    No               No     No         No\n3 Not low birth weight                    No               No     No         No\n4 Not low birth weight                    No               No     No         No\n5 Not low birth weight                    No               No     No         No\n6 Not low birth weight                    No               No     No         No\n  poverty                education insurance_type cigarettes vape allergies\n1     266             Some college         Public        Yes  Yes       Yes\n2     400 College degree or higher        Private         No   No        No\n3     190              High school         Public         No   No        No\n4     142             Some college        Private         No   No        No\n5     101              High school         Public         No   No        No\n6     142 College degree or higher         Public         No <NA>        No\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# View a data dictionary of df (variable types, levels, and labels)\ncontents(df)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<title>df Contents</title>\n<hr><h4>Data frame:df</h4>55162 observations and 16 variables, maximum # NAs:2227&emsp;&emsp;\n<hr>\n<style>\n .hmisctable989715 {\n border: 1px solid gray;\n border-collapse: collapse;\n font-size: 100%;\n }\n .hmisctable989715 td {\n text-align: right;\n padding: 0 1ex 0 1ex;\n }\n .hmisctable989715 th {\n color: Black;\n text-align: center;\n padding: 0 1ex 0 1ex;\n font-weight: bold;\n }\n </style>\n <table class=\"hmisctable989715\" border=\"1\">\n <tr><th>Name</th><th>Labels</th><th>Levels</th><th>Storage</th><th>NAs</th></tr>\n <tr><td>age</td><td>Age, years</td><td></td><td>double</td><td>   0</td></tr>\n <tr><td>age_cats</td><td>Age group</td><td><a href=\"#levels.age_cats\">4</a></td><td>integer</td><td>   0</td></tr>\n <tr><td>sex</td><td>Sex</td><td><a href=\"#levels.sex\">2</a></td><td>integer</td><td>   0</td></tr>\n <tr><td>race</td><td>Race</td><td><a href=\"#levels.race\">6</a></td><td>integer</td><td>   0</td></tr>\n <tr><td>hispanic</td><td>Hispanic or Latino origin</td><td><a href=\"#levels.hispanic\">2</a></td><td>integer</td><td>   0</td></tr>\n <tr><td>birth_weight_status</td><td>Birth weight Status</td><td><a href=\"#levels.birth_weight_status\">3</a></td><td>integer</td><td>2227</td></tr>\n <tr><td>birth_weight_very_low</td><td>Very low birth weight (less than 1,500g)</td><td><a href=\"#levels.hispanic\">2</a></td><td>integer</td><td>2227</td></tr>\n <tr><td>birth_weight_low</td><td>Low birth weight (less than 2,500g)</td><td><a href=\"#levels.hispanic\">2</a></td><td>integer</td><td>2227</td></tr>\n <tr><td>asthma</td><td>Ever Asthma Diagnosis</td><td><a href=\"#levels.hispanic\">2</a></td><td>integer</td><td> 456</td></tr>\n <tr><td>born_early</td><td>Pre-term Birth (Born 3 or more weeks before due date)</td><td><a href=\"#levels.hispanic\">2</a></td><td>integer</td><td> 543</td></tr>\n <tr><td>poverty</td><td>Familial poverty ratio</td><td></td><td>double</td><td>   0</td></tr>\n <tr><td>education</td><td>Highest level of education of adults</td><td><a href=\"#levels.education\">4</a></td><td>integer</td><td>   0</td></tr>\n <tr><td>insurance_type</td><td>Insurance Type</td><td><a href=\"#levels.insurance_type\">4</a></td><td>integer</td><td>1005</td></tr>\n <tr><td>cigarettes</td><td>Secondhand Smoking (Household smoker)</td><td><a href=\"#levels.hispanic\">2</a></td><td>integer</td><td>1102</td></tr>\n <tr><td>vape</td><td>Vaping exposure</td><td><a href=\"#levels.hispanic\">2</a></td><td>integer</td><td>1055</td></tr>\n <tr><td>allergies</td><td>Allergies</td><td><a href=\"#levels.hispanic\">2</a></td><td>integer</td><td> 147</td></tr>\n </table>\n\n<hr>\n<h5>Category Levels</h5>\n<a name=\"levels.age_cats\"><h6>age_cats</h6></a>\n<li>Infants/Toddlers (0-2)</li>\n\n<li>Preschool (3-5)</li>\n\n<li>Middle childhood (6-12)</li>\n\n<li>Teenagers (13-17)</li>\n\n<a name=\"levels.sex\"><h6>sex</h6></a>\n<li>Male</li>\n\n<li>Female</li>\n\n<a name=\"levels.race\"><h6>race</h6></a>\n<li>White</li>\n\n<li>Black or African American</li>\n\n<li>American Indian or Alaska Native</li>\n\n<li>Asian</li>\n\n<li>Native Hawaiian and other Pacific Islander</li>\n\n<li>Two or more races</li>\n\n<a name=\"levels.hispanic\"><h6>hispanic, birth_weight_very_low, birth_weight_low, asthma, born_early, cigarettes, vape, allergies</h6></a>\n<li>Yes</li>\n\n<li>No</li>\n\n<a name=\"levels.birth_weight_status\"><h6>birth_weight_status</h6></a>\n<li>Very low birth weight (less than 1,500g)</li>\n\n<li>Low birth weight (less than 2,500g)</li>\n\n<li>Not low birth weight</li>\n\n<a name=\"levels.education\"><h6>education</h6></a>\n<li>Less than high school</li>\n\n<li>High school</li>\n\n<li>Some college</li>\n\n<li>College degree or higher</li>\n\n<a name=\"levels.insurance_type\"><h6>insurance_type</h6></a>\n<li>Public</li>\n\n<li>Private</li>\n\n<li>Private and Public</li>\n\n<li>Not insured</li>\n\n```\n\n:::\n:::\n\n\n# Descriptive Statistics\n\nTo start, we created Table 1, which summarizes the characteristics of the participants by birth weight status. For each variable we report frequencies and percentages for categorical measures and means, medians, and ranges for continuous measures, allowing us to describe the sample and compare demographic, socioeconomic, and health characteristics across normal, low, and very low birth weight groups before conducting any formal analysis.\n\n## Table 1: Characteristics by Low Birth Weight Status\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Table 1\"}\n# Creates a descriptive statistics table\ntbl_summary(\n  df,\n  include = c(age, age_cats, sex, race, hispanic, born_early, poverty, \n              education, insurance_type, asthma, cigarettes, vape, allergies),\n  type = all_continuous() ~ \"continuous2\",\n  statistic = all_continuous() ~ c(\"{mean} ({sd})\", \n                                   \"{median} ({p25}-{p75})\", \n                                   \"{min}-{max}\"),\n  percent = \"column\",\n  by = birth_weight_low,               \n  missing = \"always\",        \n  missing_text = \"Missing\", \n  missing_stat = \"{N_miss} ({p_miss}%)\"\n) |>\n  add_overall() |> \n  add_n() |>                 \n  modify_header(label = \"**Participant Characteristics**\") |>\n  modify_caption(\"**Table 1: Characteristics by low birth weight Status**\") |>\n  modify_spanning_header(c(\"stat_1\", \"stat_2\") ~ \"**Low Birth Weight**\") |>\n  add_variable_group_header(\n    header = \"Environmental Exposures\",\n    variables = c(cigarettes, vape, allergies)\n  ) |>\n  modify_bold(\n    columns = label,\n    rows = (row_type == \"label\" & !variable %in% c(\"cigarettes\", \"vape\", \"allergies\")) |\n      label == \"Environmental Exposures\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gsqjpmrnak\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gsqjpmrnak table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gsqjpmrnak thead, #gsqjpmrnak tbody, #gsqjpmrnak tfoot, #gsqjpmrnak tr, #gsqjpmrnak td, #gsqjpmrnak th {\n  border-style: none;\n}\n\n#gsqjpmrnak p {\n  margin: 0;\n  padding: 0;\n}\n\n#gsqjpmrnak .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gsqjpmrnak .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gsqjpmrnak .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gsqjpmrnak .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gsqjpmrnak .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gsqjpmrnak .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gsqjpmrnak .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gsqjpmrnak .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gsqjpmrnak .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gsqjpmrnak .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gsqjpmrnak .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gsqjpmrnak .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gsqjpmrnak .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gsqjpmrnak .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gsqjpmrnak .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsqjpmrnak .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gsqjpmrnak .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gsqjpmrnak .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gsqjpmrnak .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsqjpmrnak .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gsqjpmrnak .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsqjpmrnak .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gsqjpmrnak .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsqjpmrnak .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gsqjpmrnak .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gsqjpmrnak .gt_left {\n  text-align: left;\n}\n\n#gsqjpmrnak .gt_center {\n  text-align: center;\n}\n\n#gsqjpmrnak .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gsqjpmrnak .gt_font_normal {\n  font-weight: normal;\n}\n\n#gsqjpmrnak .gt_font_bold {\n  font-weight: bold;\n}\n\n#gsqjpmrnak .gt_font_italic {\n  font-style: italic;\n}\n\n#gsqjpmrnak .gt_super {\n  font-size: 65%;\n}\n\n#gsqjpmrnak .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gsqjpmrnak .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gsqjpmrnak .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gsqjpmrnak .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gsqjpmrnak .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gsqjpmrnak .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gsqjpmrnak .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gsqjpmrnak .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gsqjpmrnak div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <caption><span data-qmd-base64=\"KipUYWJsZSAxOiBDaGFyYWN0ZXJpc3RpY3MgYnkgbG93IGJpcnRoIHdlaWdodCBTdGF0dXMqKg==\"><span class='gt_from_md'><strong>Table 1: Characteristics by low birth weight Status</strong></span></span></caption>\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipQYXJ0aWNpcGFudCBDaGFyYWN0ZXJpc3RpY3MqKg==\"><span class='gt_from_md'><strong>Participant Characteristics</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"n\"><span data-qmd-base64=\"KipOKio=\"><span class='gt_from_md'><strong>N</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gNTIsOTM1\"><span class='gt_from_md'><strong>Overall</strong><br />\nN = 52,935</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"level 1; stat_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipMb3cgQmlydGggV2VpZ2h0Kio=\"><span class='gt_from_md'><strong>Low Birth Weight</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipZZXMqKiAgCk4gPSA0LDY3OQ==\"><span class='gt_from_md'><strong>Yes</strong><br />\nN = 4,679</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipObyoqICAKTiA9IDQ4LDI1Ng==\"><span class='gt_from_md'><strong>No</strong><br />\nN = 48,256</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Age, years</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,935</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mean (SD)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">8.3 (5.3)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8.4 (5.2)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">8.3 (5.3)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1-Q3)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">8.0 (4.0-13.0)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8.0 (4.0-13.0)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">8.0 (4.0-13.0)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Min-Max</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0.0-17.0</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0.0-17.0</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0.0-17.0</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Age group</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,935</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Infants/Toddlers (0-2)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">9,179 (17%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">725 (15%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">8,454 (18%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Preschool (3-5)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">11,598 (22%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,066 (23%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">10,532 (22%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Middle childhood (6-12)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">16,948 (32%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,535 (33%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">15,413 (32%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Teenagers (13-17)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">15,210 (29%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,353 (29%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">13,857 (29%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sex</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,935</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">27,187 (51%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,189 (47%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">24,998 (52%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">25,748 (49%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,490 (53%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">23,258 (48%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Race</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,935</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    White</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">40,730 (77%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,256 (70%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">37,474 (78%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Black or African American</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3,384 (6.4%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">488 (10%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,896 (6.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    American Indian or Alaska Native</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">472 (0.9%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">49 (1.0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">423 (0.9%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Asian</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">3,334 (6.3%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">438 (9.4%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,896 (6.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Native Hawaiian and other Pacific Islander</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">226 (0.4%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">28 (0.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">198 (0.4%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Two or more races</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">4,789 (9.0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">420 (9.0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">4,369 (9.1%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Hispanic or Latino origin</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,935</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">7,626 (14%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">732 (16%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">6,894 (14%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Pre-term Birth (Born 3 or more weeks before due date)</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,584</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5,741 (11%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,873 (62%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,868 (6.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">351 (0.7%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">34 (0.7%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">317 (0.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Familial poverty ratio</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,935</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Mean (SD)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">289 (124)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">272 (131)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">291 (123)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1-Q3)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">340 (184-400)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">303 (152-400)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">340 (187-400)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Min-Max</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">50-400</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">50-400</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">50-400</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Highest level of education of adults</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,935</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Less than high school</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">1,197 (2.3%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">139 (3.0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,058 (2.2%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    High school</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">6,299 (12%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">720 (15%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">5,579 (12%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Some college</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">10,377 (20%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">988 (21%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">9,389 (19%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    College degree or higher</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">35,062 (66%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,832 (61%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">32,230 (67%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0 (0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Insurance Type</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,081</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Public</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">10,552 (20%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,248 (27%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">9,304 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Private</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">36,884 (71%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,766 (60%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">34,118 (72%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Private and Public</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,519 (4.8%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">362 (7.9%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,157 (4.5%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Not insured</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,126 (4.1%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">206 (4.5%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1,920 (4.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">854 (1.6%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">97 (2.1%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">757 (1.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Ever Asthma Diagnosis</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,532</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5,019 (9.6%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">661 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">4,358 (9.1%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">403 (0.8%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">52 (1.1%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">351 (0.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Environmental Exposures</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Secondhand Smoking (Household smoker)</td>\n<td headers=\"n\" class=\"gt_row gt_center\">51,976</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">5,393 (10%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">624 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">4,769 (10%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">959 (1.8%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">90 (1.9%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">869 (1.8%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Vaping exposure</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,020</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">2,480 (4.8%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">239 (5.2%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2,241 (4.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">915 (1.7%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">90 (1.9%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">825 (1.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Allergies</td>\n<td headers=\"n\" class=\"gt_row gt_center\">52,810</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">15,371 (29%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,418 (30%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">13,953 (29%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Missing</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">125 (0.2%)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">13 (0.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">112 (0.2%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"biAoJSk=\"><span class='gt_from_md'>n (%)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Age Distribution of Selected Children Across Households\n\nThe next thing we made was a histogram of the age distribution of the selected children across households. This showed how the sample was spread across the full 0–17 age range, with a notable peak among the youngest children (ages 0–2), reflecting the survey's oversampling of children aged 0–5. The remaining ages were fairly evenly represented, confirming that our analytic sample included children from across the pediatric age range rather than being concentrated in any single developmental stage.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Children's Age Histogram\"}\n# Histogram of Age\nggplot(df, aes(x = age)) +\n  geom_histogram(bins = 15, fill = \"lightblue\", color = \"white\") +\n  labs(title = \"Age Distribution of Selected Children Across Households\", \n       x = \"Age (Years)\", \n       y = \"Number of children\",\n       caption = \"Data from 2023 National Survey of Children's Health (NSCH)\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 11,\n                              face = \"bold\",\n                              margin = margin(b = 15),\n                              hjust = 0.5),\n    axis.title.x = element_text(margin = margin(t = 10), size = 9),\n    axis.title.y = element_text(margin = margin(r = 10), size = 9),\n    plot.caption = element_text(\n      size = 8,\n      color = \"darkgray\",\n      margin = margin(t = 15, b = 10, unit = \"pt\")\n    ))\n```\n\n::: {.cell-output-display}\n![](02_epi690a_final_project_ANALYSIS_files/figure-html/age histogram-1.png){width=576}\n:::\n:::\n\n\n## Distribution of Age by Age Group\n\nTo confirm that our age categories behaved as intended, we created a boxplot showing the distribution of age within each of the four age groups. Each group spanned its expected range with no overlap between them, verifying that children were correctly partitioned into infants and toddlers (0–2), preschool (3–5), middle childhood (6–12), and adolescents (13–17). This grouping formed the basis for our later age-stratified analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boxplot of age within group\n\nggplot(df, aes(x = age_cats, y = age)) +\n  geom_boxplot() +\n  labs(title = \"Distribution of Age by Age Group\",\n       x = \"Age Groups\",\n       y = \"Age (Years)\",\n       caption = \"Data from 2023 National Survey of Children's Health (NSCH)\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 12, face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(size = 10, color = \"gray30\", hjust = 0.5),\n    axis.text = element_text(size = 9),\n    axis.title.x = element_text(size = 9),\n    axis.title.y = element_text(size = 9),\n    legend.text = element_text(size = 9),\n    legend.title = element_text(size = 9),\n    legend.position = \"none\",\n    plot.caption = element_text(size = 8, color = \"darkgray\")\n  )\n```\n\n::: {.cell-output-display}\n![](02_epi690a_final_project_ANALYSIS_files/figure-html/unnamed-chunk-2-1.png){width=576}\n:::\n:::\n\n\n## Asthma Prevalence by Birth Weight and Age\n\nNext, we created a bar chart to see how crude asthma prevalence differed by birth weight status across the four age groups. According to the bar chart, within every age group, low-birth-weight children had a higher prevalence of ever being diagnosed with asthma than normal-birth-weight children, ranging from 5.3% versus 2.3% among infants/toddlers (0-2 years old) to 19.7% versus 14.3% among teenagers (13-17 years old). Prevalence also rose steadily with age in both groups, consistent with asthma diagnoses accumulating over childhood. This descriptive pattern set up our regression analysis, which tested whether the birth-weight gap persisted after adjusting for demographic and socioeconomic factors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  filter(!is.na(birth_weight_low), !is.na(asthma), !is.na(age_cats)) |>\n  group_by(age_cats, birth_weight_low) |>\n  summarise(pct = 100 * mean(asthma == \"Yes\"), .groups = \"drop\") |>\n  ggplot(aes(x = age_cats, y = pct, fill = birth_weight_low)) +\n  geom_col(position = position_dodge(width = 0.8), width = 0.7) +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")),\n            position = position_dodge(width = 0.8),\n            vjust = -0.4, size = 3) +\n  scale_fill_manual(values = c(\"No\" = \"steelblue\", \"Yes\" = \"lightblue\"),\n                    labels = c(\"Normal\", \"Low birth weight\")) +\n  labs(title = \"Asthma Prevalence by Birth Weight and Age Group\",\n       subtitle = \"Low-birth-weight children have higher prevalence at every age\",\n       x = NULL, y = \"% ever diagnosed with asthma\", fill = \"Birth weight\",\n       caption = \"Data from 2023 National Survey of Children's Health (NSCH)\") +\n  theme_minimal(base_size = 16) +\n  theme(\n    plot.title = element_text(size = 12, face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(size = 10, color = \"gray30\", hjust = 0.5),\n    axis.text = element_text(size = 9),\n    axis.title.y = element_text(size = 9),\n    legend.text = element_text(size = 9),\n    legend.title = element_text(size = 9),\n    legend.position = \"top\",\n    plot.caption = element_text(size = 8, color = \"darkgray\")\n  )\n```\n\n::: {.cell-output-display}\n![](02_epi690a_final_project_ANALYSIS_files/figure-html/unnamed-chunk-3-1.png){width=576}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Table 2: Unadjusted and adjusted association between low birth weight and ever having an asthma diagnosis\n\nTo formally test the association between low birth weight and asthma, we fit a staged sequence of logistic regression models, presented in Table 2. The first model was unadjusted, the second adjusted for child age, and the third adjusted for the full set of covariates (sex, race, preterm birth, familial poverty ratio, parental education, insurance type, and household smoker status). For each model we report both the odds ratio and the absolute prevalence difference with 95% confidence intervals, since the two measures convey complementary information about the relative and absolute magnitude of the association.\n\nLow birth weight was significantly associated with ever having an asthma diagnosis across all three models. The unadjusted odds ratio was 1.67 (95% CI 1.52–1.82) and was essentially unchanged after adjusting for age (OR 1.67, 95% CI 1.53–1.83), indicating that age did not confound the relationship. After full adjustment, the association attenuated to an odds ratio of 1.21 (95% CI 1.08–1.35) but remained statistically significant, indicating that much of the crude association was explained by demographic and socioeconomic factors while an independent association persisted; this pattern of attenuation across the three models is shown graphically in @fig-forest-models in the appendix. On the absolute scale, low-birth-weight children had roughly a 5 percentage-point higher probability of asthma than normal-birth-weight children.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl <- tribble(\n  ~birth_weight,         ~events,       ~unadj_pd,          ~unadj_or,          ~age_pd,            ~age_or,            ~all_pd,            ~all_or,\n  \"Normal birth weight\", \"4,358 (9.1)\", \"Reference\",        \"1.00\",             \"Reference\",        \"1.00\",             \"Reference\",        \"1.00\",\n  \"Low birth weight\",    \"661 (14.3)\",  \"5.2 (4.1 to 6.2)\", \"1.67 (1.52–1.82)\", \"5.1 (4.1 to 6.1)\", \"1.67 (1.53–1.83)\", \"1.68 (0.66–2.71)\", \"1.21 (1.08–1.35)\",\n  \"Missing\",             \"190 (8.7)\",   \"\",                 \"\",                 \"\",                 \"\",                 \"\",                 \"\"\n)\n\ntbl |>\n  gt(rowname_col = \"birth_weight\") |>\n  # Row-group label that spans the exposure rows\n  tab_row_group(\n    label = md(\"**Exposure = birth weight category**\"),\n    rows  = everything()\n  ) |>\n  # Top-level spanning headers\n  tab_spanner(label = \"Events, N=52,935\",           columns = events) |>\n  tab_spanner(label = \"Unadjusted, N=52,532\",        columns = c(unadj_pd, unadj_or)) |>\n  tab_spanner(label = \"Adjusted for age, N=52,532\",  columns = c(age_pd, age_or)) |>\n  tab_spanner(label = \"Adjusted for all variables,* N=50,580\",\n              id = \"all_var\", columns = c(all_pd, all_or)) |>\n  # Sub-column labels\n  cols_label(\n    events   = \"\",\n    unadj_pd = \"Prevalence difference % (95% CI)\",\n    unadj_or = \"Odds ratio (95% CI)\",\n    age_pd   = \"Prevalence difference % (95% CI)\",\n    age_or   = \"Odds ratio (95% CI)\",\n    all_pd   = \"Prevalence difference % (95% CI)\",\n    all_or   = \"Odds ratio (95% CI)\"\n  ) |>\n  cols_align(align = \"center\", columns = -birth_weight) |>\n  # The asterisk footnote\n  tab_footnote(\n    footnote  = \"Abbreviations, CI = Confidence interval\",\n    locations = cells_column_spanners(spanners = \"all_var\")\n  ) |>\n  tab_footnote(\n    footnote  = \"Unadjusted and adjusted results were estimated using logistic regression\",\n    locations = cells_stub(rows = birth_weight == \"Low birth weight\")\n  ) |>\n  tab_footnote(\n    footnote  = \"Adjusted for age, sex, race, preterm birth, familial poverty ratio, education level of adults, insurance type, andhousehold smoker status\",\n    locations = cells_stub(rows = birth_weight == \"Low birth weight\")\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"baohphbmoi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#baohphbmoi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#baohphbmoi thead, #baohphbmoi tbody, #baohphbmoi tfoot, #baohphbmoi tr, #baohphbmoi td, #baohphbmoi th {\n  border-style: none;\n}\n\n#baohphbmoi p {\n  margin: 0;\n  padding: 0;\n}\n\n#baohphbmoi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#baohphbmoi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#baohphbmoi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#baohphbmoi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#baohphbmoi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#baohphbmoi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#baohphbmoi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#baohphbmoi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#baohphbmoi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#baohphbmoi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#baohphbmoi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#baohphbmoi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#baohphbmoi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#baohphbmoi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#baohphbmoi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#baohphbmoi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#baohphbmoi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#baohphbmoi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#baohphbmoi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#baohphbmoi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#baohphbmoi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#baohphbmoi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#baohphbmoi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#baohphbmoi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#baohphbmoi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#baohphbmoi .gt_left {\n  text-align: left;\n}\n\n#baohphbmoi .gt_center {\n  text-align: center;\n}\n\n#baohphbmoi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#baohphbmoi .gt_font_normal {\n  font-weight: normal;\n}\n\n#baohphbmoi .gt_font_bold {\n  font-weight: bold;\n}\n\n#baohphbmoi .gt_font_italic {\n  font-style: italic;\n}\n\n#baohphbmoi .gt_super {\n  font-size: 65%;\n}\n\n#baohphbmoi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#baohphbmoi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#baohphbmoi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#baohphbmoi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#baohphbmoi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#baohphbmoi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#baohphbmoi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#baohphbmoi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#baohphbmoi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Events, N=52,935\">\n        <div class=\"gt_column_spanner\">Events, N=52,935</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Unadjusted, N=52,532\">\n        <div class=\"gt_column_spanner\">Unadjusted, N=52,532</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Adjusted for age, N=52,532\">\n        <div class=\"gt_column_spanner\">Adjusted for age, N=52,532</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"all_var\">\n        <div class=\"gt_column_spanner\">Adjusted for all variables,* N=50,580<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"events\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"unadj_pd\">Prevalence difference % (95% CI)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"unadj_or\">Odds ratio (95% CI)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age_pd\">Prevalence difference % (95% CI)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age_or\">Odds ratio (95% CI)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"all_pd\">Prevalence difference % (95% CI)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"all_or\">Odds ratio (95% CI)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"8\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"&lt;span data-qmd-base64=&quot;KipFeHBvc3VyZSA9IGJpcnRoIHdlaWdodCBjYXRlZ29yeSoq&quot;&gt;&lt;span class='gt_from_md'&gt;&lt;strong&gt;Exposure = birth weight category&lt;/strong&gt;&lt;/span&gt;&lt;/span&gt;\"><span data-qmd-base64=\"KipFeHBvc3VyZSA9IGJpcnRoIHdlaWdodCBjYXRlZ29yeSoq\"><span class='gt_from_md'><strong>Exposure = birth weight category</strong></span></span></th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Normal birth weight</th>\n<td headers=\"**Exposure = birth weight category** stub_1_1 events\" class=\"gt_row gt_center\">4,358 (9.1)</td>\n<td headers=\"**Exposure = birth weight category** stub_1_1 unadj_pd\" class=\"gt_row gt_center\">Reference</td>\n<td headers=\"**Exposure = birth weight category** stub_1_1 unadj_or\" class=\"gt_row gt_center\">1.00</td>\n<td headers=\"**Exposure = birth weight category** stub_1_1 age_pd\" class=\"gt_row gt_center\">Reference</td>\n<td headers=\"**Exposure = birth weight category** stub_1_1 age_or\" class=\"gt_row gt_center\">1.00</td>\n<td headers=\"**Exposure = birth weight category** stub_1_1 all_pd\" class=\"gt_row gt_center\">Reference</td>\n<td headers=\"**Exposure = birth weight category** stub_1_1 all_or\" class=\"gt_row gt_center\">1.00</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Low birth weight<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2,3</sup></span></th>\n<td headers=\"**Exposure = birth weight category** stub_1_2 events\" class=\"gt_row gt_center\">661 (14.3)</td>\n<td headers=\"**Exposure = birth weight category** stub_1_2 unadj_pd\" class=\"gt_row gt_center\">5.2 (4.1 to 6.2)</td>\n<td headers=\"**Exposure = birth weight category** stub_1_2 unadj_or\" class=\"gt_row gt_center\">1.67 (1.52–1.82)</td>\n<td headers=\"**Exposure = birth weight category** stub_1_2 age_pd\" class=\"gt_row gt_center\">5.1 (4.1 to 6.1)</td>\n<td headers=\"**Exposure = birth weight category** stub_1_2 age_or\" class=\"gt_row gt_center\">1.67 (1.53–1.83)</td>\n<td headers=\"**Exposure = birth weight category** stub_1_2 all_pd\" class=\"gt_row gt_center\">1.68 (0.66–2.71)</td>\n<td headers=\"**Exposure = birth weight category** stub_1_2 all_or\" class=\"gt_row gt_center\">1.21 (1.08–1.35)</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\">Missing</th>\n<td headers=\"**Exposure = birth weight category** stub_1_3 events\" class=\"gt_row gt_center\">190 (8.7)</td>\n<td headers=\"**Exposure = birth weight category** stub_1_3 unadj_pd\" class=\"gt_row gt_center\"></td>\n<td headers=\"**Exposure = birth weight category** stub_1_3 unadj_or\" class=\"gt_row gt_center\"></td>\n<td headers=\"**Exposure = birth weight category** stub_1_3 age_pd\" class=\"gt_row gt_center\"></td>\n<td headers=\"**Exposure = birth weight category** stub_1_3 age_or\" class=\"gt_row gt_center\"></td>\n<td headers=\"**Exposure = birth weight category** stub_1_3 all_pd\" class=\"gt_row gt_center\"></td>\n<td headers=\"**Exposure = birth weight category** stub_1_3 all_or\" class=\"gt_row gt_center\"></td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"8\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> Abbreviations, CI = Confidence interval</td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"8\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> Unadjusted and adjusted results were estimated using logistic regression</td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"8\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>3</sup></span> Adjusted for age, sex, race, preterm birth, familial poverty ratio, education level of adults, insurance type, andhousehold smoker status</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Logistic Regression\n\nHaving summarized the results in Table 2, we present the full logistic regression models below. Each model is shown in a staged sequence (unadjusted, age-adjusted, and fully adjusted) with the complete model output and the odds ratios and confidence intervals for every term.\n\nWe used logistic regression because our outcome, ever having an asthma diagnosis, is binary. To separate the effect of low birth weight from the influence of other factors, we built the models in a staged sequence rather than fitting a single model. The first model was unadjusted, estimating the crude association between low birth weight and asthma. The second added child age alone, since age was fully observed and allowed us to check whether it confounded the relationship before introducing covariates with missing data. The third model was fully adjusted for sex, race, preterm birth, familial poverty ratio, parental education, insurance type, and household smoker status. Building the models in stages let us see how the association changed as covariates were added and to account for the effect of missing covariate data on the sample size at each step.\n\n### Model 1: Unadjusted\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Relevel binary variables so \"No\" is the reference category\n# This makes every odds ratio read in the intuitive direction (exposed vs. unexposed).\n\ndf$birth_weight_low <- relevel(df$birth_weight_low, ref = \"No\")  # OR = low vs normal birth weight\ndf$born_early       <- relevel(df$born_early, ref = \"No\")        # OR = preterm vs full-term\ndf$asthma           <- relevel(df$asthma, ref = \"No\")            # model P(asthma = Yes)\ndf$cigarettes       <- relevel(df$cigarettes, ref = \"No\")        # OR = smoker vs non-smoker household\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: unadjusted asthma on low birth weight\nmodel1 <- glm(asthma ~ birth_weight_low, data = df, family = binomial)\n\n# full model output (coefficients, SEs, fit stats)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = asthma ~ birth_weight_low, family = binomial, data = df)\n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -2.30183    0.01589 -144.88   <2e-16 ***\nbirth_weight_lowYes  0.51007    0.04492   11.36   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 33114  on 52531  degrees of freedom\nResidual deviance: 32996  on 52530  degrees of freedom\n  (2630 observations deleted due to missingness)\nAIC: 33000\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\n# odds ratio + 95% CI\ntidy(model1, exponentiate = TRUE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term                estimate std.error statistic  p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)            0.100    0.0159    -145.  0          0.0970     0.103\n2 birth_weight_lowYes    1.67     0.0449      11.4 6.92e-30   1.52       1.82 \n```\n\n\n:::\n:::\n\n\n***Interpretation:***\n\n- *Model 1 is unadjusted and shows a significant association between birth weight status and asthma (OR = 1.67, 95% CI: 1.52–1.82, p \\< 0.001).*\n- *The reference level is normal birth weight, so this OR compares low-birth-weight children to normal-birth-weight children.*\n- *Interpretation: low-birth-weight children had about 1.67× the odds of an asthma diagnosis compared to normal-birth-weight children.*\n- *This is consistent with the crude prevalences (14.3% asthma among low-birth-weight children vs 9.1% among normal-birth-weight children) and with the study hypothesis.*\n\n### Model 2: Adjusted for Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 2: asthma on low birth weight, age-adjusted\nmodel2 <- glm(asthma ~ birth_weight_low + age, data = df, family = binomial)\n\n# full model output (coefficients, SEs, fit stats)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = asthma ~ birth_weight_low + age, family = binomial, \n    data = df)\n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)         -3.198173   0.034571  -92.51   <2e-16 ***\nbirth_weight_lowYes  0.515786   0.045582   11.32   <2e-16 ***\nage                  0.095284   0.002922   32.60   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 33114  on 52531  degrees of freedom\nResidual deviance: 31875  on 52529  degrees of freedom\n  (2630 observations deleted due to missingness)\nAIC: 31881\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\n# odds ratios + 95% CIs for every term\ntidy(model2, exponentiate = TRUE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term                estimate std.error statistic   p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)           0.0408   0.0346      -92.5 0           0.0381    0.0437\n2 birth_weight_lowYes   1.67     0.0456       11.3 1.10e- 29   1.53      1.83  \n3 age                   1.10     0.00292      32.6 3.65e-233   1.09      1.11  \n```\n\n\n:::\n:::\n\n\n**Interpretation:**\n\n- *Model 2 adds age as a covariate. After adjusting for age, the birth weight association is essentially unchanged: OR = 1.67 (95% CI: 1.53–1.83, p \\< 0.001), nearly identical to Model 1.*\n- *Low-birth-weight children had about 1.67× the odds of an asthma diagnosis compared to normal-birth-weight children.*\n- *Age is significant: OR = 1.10 per year (95% CI: 1.09–1.11, p \\< 0.001), so each additional year is associated with about 10% higher odds of an ever asthma diagnosis.*\n- *Because the birth weight OR is stable after adjusting for age, age is not confounding the birth weight–asthma relationship.*\n\n### Model 3: Adjusted for age, sex, race, preterm birth, familial poverty ratio, education level of adults, insurance type, and household smoker status\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 3: fully adjusted logistic regression of asthma\nmodel3 <- glm(asthma ~ birth_weight_low + age + sex + race + born_early \n              + poverty + education + insurance_type + cigarettes, \n              data = df, family = binomial) \n\n# full model output (coefficients, SEs, fit stats)\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = asthma ~ birth_weight_low + age + sex + race + \n    born_early + poverty + education + insurance_type + cigarettes, \n    family = binomial, data = df)\n\nCoefficients:\n                                                 Estimate Std. Error z value\n(Intercept)                                    -3.1357821  0.1128916 -27.777\nbirth_weight_lowYes                             0.1924289  0.0565695   3.402\nage                                             0.0967118  0.0030398  31.816\nsexFemale                                      -0.3610196  0.0314118 -11.493\nraceBlack or African American                   0.6256013  0.0528833  11.830\nraceAmerican Indian or Alaska Native            0.1853417  0.1486602   1.247\nraceAsian                                      -0.1984254  0.0718400  -2.762\nraceNative Hawaiian and other Pacific Islander  0.1894889  0.2191447   0.865\nraceTwo or more races                           0.3315935  0.0510043   6.501\nborn_earlyYes                                   0.4830075  0.0505906   9.547\npoverty                                        -0.0001191  0.0001605  -0.742\neducationHigh school                            0.1671360  0.1115279   1.499\neducationSome college                           0.2721560  0.1091599   2.493\neducationCollege degree or higher               0.2023212  0.1098820   1.841\ninsurance_typePrivate                          -0.2991717  0.0468320  -6.388\ninsurance_typePrivate and Public                0.1712852  0.0676474   2.532\ninsurance_typeNot insured                      -0.4262429  0.0876601  -4.862\ncigarettesYes                                   0.0942504  0.0479862   1.964\n                                               Pr(>|z|)    \n(Intercept)                                     < 2e-16 ***\nbirth_weight_lowYes                             0.00067 ***\nage                                             < 2e-16 ***\nsexFemale                                       < 2e-16 ***\nraceBlack or African American                   < 2e-16 ***\nraceAmerican Indian or Alaska Native            0.21249    \nraceAsian                                       0.00574 ** \nraceNative Hawaiian and other Pacific Islander  0.38722    \nraceTwo or more races                          7.96e-11 ***\nborn_earlyYes                                   < 2e-16 ***\npoverty                                         0.45814    \neducationHigh school                            0.13398    \neducationSome college                           0.01266 *  \neducationCollege degree or higher               0.06558 .  \ninsurance_typePrivate                          1.68e-10 ***\ninsurance_typePrivate and Public                0.01134 *  \ninsurance_typeNot insured                      1.16e-06 ***\ncigarettesYes                                   0.04952 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 31777  on 50579  degrees of freedom\nResidual deviance: 29985  on 50562  degrees of freedom\n  (4582 observations deleted due to missingness)\nAIC: 30021\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\n# odds ratios + 95% CIs for every term\ntidy(model3, exponentiate = TRUE, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 18 × 7\n   term                estimate std.error statistic   p.value conf.low conf.high\n   <chr>                  <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n 1 (Intercept)           0.0435  0.113      -27.8   8.24e-170   0.0347    0.0540\n 2 birth_weight_lowYes   1.21    0.0566       3.40  6.70e-  4   1.08      1.35  \n 3 age                   1.10    0.00304     31.8   3.94e-222   1.10      1.11  \n 4 sexFemale             0.697   0.0314     -11.5   1.43e- 30   0.655     0.741 \n 5 raceBlack or Afric…   1.87    0.0529      11.8   2.74e- 32   1.68      2.07  \n 6 raceAmerican India…   1.20    0.149        1.25  2.12e-  1   0.890     1.60  \n 7 raceAsian             0.820   0.0718      -2.76  5.74e-  3   0.711     0.942 \n 8 raceNative Hawaiia…   1.21    0.219        0.865 3.87e-  1   0.769     1.82  \n 9 raceTwo or more ra…   1.39    0.0510       6.50  7.96e- 11   1.26      1.54  \n10 born_earlyYes         1.62    0.0506       9.55  1.33e- 21   1.47      1.79  \n11 poverty               1.00    0.000160    -0.742 4.58e-  1   1.00      1.00  \n12 educationHigh scho…   1.18    0.112        1.50  1.34e-  1   0.954     1.48  \n13 educationSome coll…   1.31    0.109        2.49  1.27e-  2   1.06      1.63  \n14 educationCollege d…   1.22    0.110        1.84  6.56e-  2   0.991     1.53  \n15 insurance_typePriv…   0.741   0.0468      -6.39  1.68e- 10   0.676     0.813 \n16 insurance_typePriv…   1.19    0.0676       2.53  1.13e-  2   1.04      1.35  \n17 insurance_typeNot …   0.653   0.0877      -4.86  1.16e-  6   0.548     0.773 \n18 cigarettesYes         1.10    0.0480       1.96  4.95e-  2   0.999     1.21  \n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\n***Main finding — birth weight (fully adjusted):***\n\n- *After full adjustment, the association attenuates from 1.67 to OR = 1.21 (95% CI 1.08–1.35, p \\< 0.001) but remains significant.*\n\n- *Low-birth-weight children have \\~1.21× the odds of asthma vs normal-birth-weight children.*\n\n- *The drop from 1.67 → 1.21 means much of the crude association is explained by the other covariates, but an independent association persists.*\n\n***Other significant predictors (CI excludes 1):***\n\n- *Age: OR = 1.10/year — \\~10% higher odds per additional year of age.*\n\n- *Sex (Female): OR = 0.70 — girls have lower odds than boys.*\n\n- *Race (vs White): Black = 1.87 (higher); Asian = 0.82 (lower); Two or more races = 1.39 (higher).*\n\n- *Preterm birth (Yes): OR = 1.62 — premature children have higher odds.*\n\n- *Education (Some college): OR = 1.31 (higher vs reference).*\n\n- *Insurance (vs Public): Private = 0.74 (lower); Private and Public = 1.19 (higher); Not insured = 0.65 (lower).*\n\n- *Household smoker (Yes): OR = 1.10 (95% CI 1.00–1.21, p = 0.05) — \\~10% higher odds, but right at the significance threshold.*\n\n***Not significant (CI crosses 1):***\n\n- *Poverty (\\~1.00), American Indian/Alaska Native, Native Hawaiian/Pacific Islander, and High school and College-degree education.*\n\n### Model 3 Visualizations\n\nTo make the model results easier to interpret, we created several visualizations. First, a predicted-probability plot shows how the estimated probability of an asthma diagnosis changes across age for low- versus normal-birth-weight children, translating the model's odds ratios onto the more intuitive probability scale. Second, a coefficient plot displays the adjusted odds ratios for every predictor in the fully adjusted model on a single axis, allowing quick comparison of which factors raise or lower the odds of asthma and which are statistically significant. Together, these plots summarize the fully adjusted model both in terms of its central finding (the birth-weight effect across age) and its full set of covariates.\n\n#### Predicted Probabilities Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predicted asthma probability by age and birth weight (Model 3)\nplot_predictions(model3, condition = c(\"age\", \"birth_weight_low\")) +\n  scale_color_discrete(labels = c(\"Normal\", \"Low birth weight\")) +\n  scale_fill_discrete(labels = c(\"Normal\", \"Low birth weight\")) +\n  labs(title = \"Predicted Asthma Probability by Age and Birth Weight\",\n       subtitle = \"Low-birth-weight children have higher predicted probability at every age\",\n       x = \"Age (Years)\", y = \"Predicted probability of asthma\",\n       color = \"Birth weight\", fill = \"Birth weight\",\n       caption = \"Adjusted model (Model 3). Data from 2023 NSCH\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 12,\n                              face = \"bold\",\n                              hjust = 0.5),\n    plot.subtitle = element_text(size = 10, hjust = 0.5),\n    axis.title.x = element_text(margin = margin(t = 10), size = 10),\n    axis.title.y = element_text(margin = margin(r = 10), size = 10),\n    plot.caption = element_text(\n      size = 9,\n      color = \"darkgray\",\n      margin = margin(t = 15, b = 10, unit = \"pt\")\n    ))\n```\n\n::: {.cell-output-display}\n![](02_epi690a_final_project_ANALYSIS_files/figure-html/unnamed-chunk-9-1.png){width=576}\n:::\n:::\n\n\n***Interpretation:***\n\n- *Predicted asthma probability rises steadily with age in both groups, from about 4–5% at birth to 16–19% by age 17 — consistent with the age odds ratio of 1.10 (asthma diagnoses accumulate as children get older).*\n\n- *Low-birth-weight children (blue) sit above normal-birth-weight children (red) at every age, showing the adjusted birth-weight effect (OR = 1.21) holds across all of childhood.*\n\n- *The gap between the two curves widens in absolute terms at older ages — expected on the probability scale, since a constant odds ratio produces a larger percentage-point difference when the baseline probability is higher.*\n\n- *The confidence bands overlap modestly, reflecting that the adjusted birth-weight association, while significant, is smaller than the crude one.*\n\n#### Coefficient Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabels <- c(\n  \"birth_weight_lowYes\" = \"Low birth weight\",\n  \"age\" = \"Age (per year)\",\n  \"sexFemale\" = \"Female\",\n  \"raceBlack or African American\" = \"Black\",\n  \"raceAmerican Indian or Alaska Native\" = \"American Indian/Alaska Native\",\n  \"raceAsian\" = \"Asian\",\n  \"raceNative Hawaiian and other Pacific Islander\" = \"Native Hawaiian/Pacific Islander\",\n  \"raceTwo or more races\" = \"Two or more races\",\n  \"born_earlyYes\" = \"Preterm birth\",\n  \"poverty\" = \"Poverty ratio\",\n  \"educationHigh school\" = \"High school\",\n  \"educationSome college\" = \"Some college\",\n  \"educationCollege degree or higher\" = \"College degree or higher\",\n  \"insurance_typePrivate\" = \"Private insurance\",\n  \"insurance_typePrivate and Public\" = \"Private and public insurance\",\n  \"insurance_typeNot insured\" = \"Not insured\",\n  \"cigarettesYes\" = \"Household smoker\"\n)\n\nmodelplot(model3, coef_map = rev(labels), exponentiate = TRUE) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"gray50\") +\n  labs(title = \"Adjusted Odds Ratios for Ever Asthma Diagnosis (Model 3)\",\n       subtitle = \"Reference line at OR = 1; intervals crossing it are not significant\",\n       x = \"Odds ratio (95% CI)\", y = NULL,\n       caption = \"Model 3 (fully adjusted). Data from 2023 NSCH\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 11, face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(size = 9, hjust = 0.5),\n    axis.title.x = element_text(margin = margin(t = 10), size = 9),\n    plot.caption = element_text(size = 8, color = \"darkgray\",\n                                margin = margin(t = 15, b = 10, unit = \"pt\"))\n  )\n```\n\n::: {.cell-output-display}\n![](02_epi690a_final_project_ANALYSIS_files/figure-html/unnamed-chunk-10-1.png){width=576}\n:::\n:::\n\n\n**Interpretation**\n\n- *Each point is a covariate's adjusted odds ratio from Model 3, with its 95% CI; the dashed line at OR = 1 marks no association, and intervals crossing it are not statistically significant.*\n\n- ***Higher asthma odds (right of 1, CI excludes 1):** Black race shows the largest increase (OR \\~1.87), followed by preterm birth (\\~1.62), two or more races (\\~1.39), some college (\\~1.31), private and public insurance (\\~1.19), low birth weight (\\~1.21), and age (\\~1.10 per year).*\n\n- ***Lower asthma odds (left of 1, CI excludes 1):** female sex (\\~0.70), Asian race (\\~0.82), private insurance (\\~0.74), and not insured (\\~0.65).*\n\n- ***On the significance boundary:** household smoker (\\~1.10) sits just right of 1 with its CI lower bound touching 1 — a borderline positive association.*\n\n- ***No significant association (CI crosses 1):** poverty ratio (\\~1.00), American Indian/Alaska Native, Native Hawaiian/Pacific Islander, high school, and college degree or higher.*\n\n- *Overall, the strongest independent predictors of asthma in the fully adjusted model are Black race and preterm birth, while low birth weight — the exposure of interest — remains modestly but significantly associated after accounting for all covariates.*\n\n------------------------------------------------------------------------\n\n## Odds Ratios\n\nTo compare the birth-weight association directly across the three models, we extracted the odds ratio and 95% confidence interval for low birth weight from each one and reported them alongside each model's sample size. Isolating this single term across the unadjusted, age-adjusted, and fully adjusted models lets us see how the estimate changed as covariates were added, while the sample sizes show how covariate missingness reduced the analytic sample at the fully adjusted stage.\n\nWe then created a forest plot of the fully adjusted model, displaying the adjusted odds ratio and confidence interval for every predictor on a single axis. Plotting all covariates together, with a reference line at an odds ratio of 1, makes it easy to see which factors were associated with higher or lower odds of asthma and which were statistically significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverall <- bind_rows(\n  tidy(model1, exponentiate = TRUE, conf.int = TRUE) |> mutate(model = \"Unadjusted\"),\n  tidy(model2, exponentiate = TRUE, conf.int = TRUE) |> mutate(model = \"Age-adjusted\"),\n  tidy(model3, exponentiate = TRUE, conf.int = TRUE) |> mutate(model = \"Fully adjusted\")\n) |>\n  filter(str_detect(term, \"birth_weight_low\")) |>\n  mutate(model = factor(model, levels = c(\"Fully adjusted\", \"Age-adjusted\", \"Unadjusted\")))\n\nggplot(overall, aes(x = estimate, y = model)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"gray50\") +\n  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +\n  labs(title = \"Low Birth Weight and Asthma Odds Across Models\",\n       subtitle = \"Association attenuates with adjustment but remains significant\",\n       x = \"Odds ratio (95% CI)\", y = NULL,\n       caption = \"Data from 2023 National Survey of Children's Health (NSCH)\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 11,\n                              face = \"bold\",\n                              hjust = 0.5),\n    plot.subtitle = element_text(size = 10, hjust = 0.5),\n    axis.title.x = element_text(margin = margin(t = 10), size = 9),\n    axis.title.y = element_text(margin = margin(r = 10), size = 9),\n    plot.caption = element_text(\n      size = 8,\n      color = \"darkgray\",\n      margin = margin(t = 15, b = 10, unit = \"pt\")\n    ))\n```\n\n::: {.cell-output-display}\n![](02_epi690a_final_project_ANALYSIS_files/figure-html/unnamed-chunk-11-1.png){width=576}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: odds ratio + CI for low birth weight\ntidy(model1, exponentiate = TRUE, conf.int = TRUE) |> \n  filter(str_detect(term, \"birth_weight_low\")) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  term                estimate std.error statistic  p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 birth_weight_lowYes     1.67    0.0449      11.4 6.92e-30     1.52      1.82\n```\n\n\n:::\n\n```{.r .cell-code}\n# Model 2: same, age-adjusted\ntidy(model2, exponentiate = TRUE, conf.int = TRUE) |> \n  filter(str_detect(term, \"birth_weight_low\")) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  term                estimate std.error statistic  p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 birth_weight_lowYes     1.67    0.0456      11.3 1.10e-29     1.53      1.83\n```\n\n\n:::\n\n```{.r .cell-code}\n# Model 3: same, fully adjusted\ntidy(model3, exponentiate = TRUE, conf.int = TRUE) |> \n  filter(str_detect(term, \"birth_weight_low\")) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  term                estimate std.error statistic  p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 birth_weight_lowYes     1.21    0.0566      3.40 0.000670     1.08      1.35\n```\n\n\n:::\n\n```{.r .cell-code}\n# sample size for each model\nnobs(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 52532\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 52532\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50580\n```\n\n\n:::\n:::\n\n\n***Interpretation***\n\n- *The birth weight–asthma association is significant in all three models and consistent in direction (reference = low birth weight, so not-low-birth-weight children have higher odds).*\n\n- *Adjusting for age alone changes nothing (1.67 → 1.67) — age is not a confounder.*\n\n- *Full adjustment attenuates the OR from 1.67 to 1.21, so demographic and socioeconomic covariates explain a substantial part of the crude association, though a significant independent association remains.*\n\n- *One caveat to note: Model 3 dropped \\~1,952 observations (52,532 → 50,580) due to missing data on the added covariates, so it isn't fit on quite the same sample as Models 1–2. The comparison is still valid but not strictly apples-to-apples.*\n\n------------------------------------------------------------------------\n\n## Prevalence Difference % (95% CI)\n\nBecause odds ratios describe the association on a relative scale, we also estimated the absolute difference in asthma probability between low- and normal-birth-weight children. We first computed this contrast using predicted probabilities from `predictions()` and a hypothesis test, which evaluates the difference at a single representative covariate profile. We then computed it as an average marginal effect using `avg_comparisons()`, which averages the difference in predicted probability across all children in the sample using their actual covariate values. Because the average marginal effect reflects the true covariate distribution of the sample and provides a more precise population-level estimate, we report the `avg_comparisons()` results in Table 2. Reporting the prevalence difference alongside the odds ratio conveys the absolute public-health impact of low birth weight, which the odds ratio alone does not capture.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: Unadjusted ===============================================\n# predicted asthma probability, No vs Yes\npred_model1 <- predictions(model1, \n                           newdata = datagrid(\n                             birth_weight_low = c(\"No\", \"Yes\")))\n\n# Checks if the two predictions differ\nhypotheses(pred_model1, hypothesis = \"b2 = b1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Hypothesis Estimate Std. Error    z Pr(>|z|)   S   2.5 % 97.5 %\n      b2=b1   0.0519     0.0449 1.16    0.248 2.0 -0.0361   0.14\n```\n\n\n:::\n\n```{.r .cell-code}\n# Model 2: Age-adjusted =============================================\n# same predictions, now controlling for age\npred_model2 <- predictions(model2, \n                           newdata = datagrid(\n                             birth_weight_low = c(\"No\", \"Yes\")))\n\n# Checks if the two predictions differ\nhypotheses(pred_model2, hypothesis = \"b2 = b1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Hypothesis Estimate Std. Error    z Pr(>|z|)   S  2.5 % 97.5 %\n      b2=b1   0.0474     0.0456 1.04    0.299 1.7 -0.042  0.137\n```\n\n\n:::\n\n```{.r .cell-code}\n# Model 3: Fully adjusted (multiple covariates) =====================\n# same predictions, now controlling for *almost* everything\npred_model3 <- predictions(model3, \n                           newdata = datagrid(\n                             birth_weight_low = c(\"No\", \"Yes\")))\n\n# Checks if the two predictions differ\nhypotheses(pred_model3, hypothesis = \"b2 = b1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Hypothesis Estimate Std. Error    z Pr(>|z|)   S   2.5 % 97.5 %\n      b2=b1   0.0147     0.0566 0.26    0.795 0.3 -0.0962  0.126\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Event counts for the full sample\ndf |>\n  group_by(birth_weight_low) |>\n  summarise(n = n(),\n            events = sum(asthma == \"Yes\", na.rm = TRUE),\n            pct = round(100 * events / sum(!is.na(asthma)), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  birth_weight_low     n events   pct\n  <fct>            <int>  <int> <dbl>\n1 No               48256   4358   9.1\n2 Yes               4679    661  14.3\n3 <NA>              2227    190   8.7\n```\n\n\n:::\n\n```{.r .cell-code}\n# Adjusted prevalence differences (probability scale), Low vs Normal\navg_comparisons(model1, variables = \"birth_weight_low\")     # unadjusted\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)    S  2.5 % 97.5 %\n   0.0519    0.00531 9.77   <0.001 72.5 0.0415 0.0623\n\nTerm: birth_weight_low\nType: response\nComparison: Yes - No\n```\n\n\n:::\n\n```{.r .cell-code}\navg_comparisons(model2, variables = \"birth_weight_low\")     # adjusted\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error   z Pr(>|z|)    S  2.5 % 97.5 %\n    0.051     0.0052 9.8   <0.001 72.9 0.0408 0.0612\n\nTerm: birth_weight_low\nType: response\nComparison: Yes - No\n```\n\n\n:::\n\n```{.r .cell-code}\navg_comparisons(model3, variables = \"birth_weight_low\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S   2.5 % 97.5 %\n   0.0168    0.00524 3.22   0.0013 9.6 0.00658 0.0271\n\nTerm: birth_weight_low\nType: response\nComparison: Yes - No\n```\n\n\n:::\n:::\n\n\n***Interpretation***\n\n- *On the absolute (probability) scale, low-birth-weight children have about 5 percentage points higher predicted probability of asthma than normal-birth-weight children.*\n- *This difference is statistically significant in the unadjusted and age-adjusted models (prevalence difference ≈ 5.1–5.2 pp, 95% CI roughly 4–6 pp, p \\< 0.001).*\n- *The absolute prevalence difference is consistent with the crude prevalences (14.3% vs 9.1%) and with the odds ratios — both scales agree that low birth weight is associated with higher asthma risk.*\n- *Reporting both measures is useful because the odds ratio captures the relative association while the prevalence difference conveys the absolute public-health impact.*\n\n------------------------------------------------------------------------\n\n# Table 3. Adjusted Associations between Birth Weight Status and Ever Asthma Diagnosis, Stratified by Age Group\\*\n\nBecause asthma diagnoses accumulate over childhood and younger children have had less time to be diagnosed, we conducted a parallel analysis stratified by age group to examine whether the association between low birth weight and asthma differed across developmental stages. We repeated the fully adjusted model separately within each of the four age strata (infants and toddlers \\[0–2\\], preschool \\[3–5\\], middle childhood \\[6–12\\], and adolescents \\[13–17\\]) excluding age from the covariate set, since age no longer varies meaningfully within a stratum. As in Table 2, we report both the odds ratio and the absolute prevalence difference with 95% confidence intervals for each age group, summarized in Table 3. The individual stratified models are shown below.\n\n+-------------------+---------------------+---------------+--------------------------+------------------+\n| Age group         | Birth weight status | Events, N (%) | Prevalence difference %\\ | Odds ratio\\      |\n|                   |                     |               | (95% CI)                 | (95% CI)         |\n+===================+=====================+===============+==========================+==================+\n| Toddler\\          | Normal birth weight | 193 (2.3%)    | Reference                | 1.00             |\n| (0-2 years)       |                     |               |                          |                  |\n+-------------------+---------------------+---------------+--------------------------+------------------+\n|                   | Low birth weight    | 38 (5.3%)     | 0.8 (−0.5 to 2.2)        | 1.37 (0.86–2.14) |\n+-------------------+---------------------+---------------+--------------------------+------------------+\n| Preschool\\        | Normal birth weight | 671 (6.4%)    | Reference                | 1.00             |\n| (3-5 years)       |                     |               |                          |                  |\n+-------------------+---------------------+---------------+--------------------------+------------------+\n|                   | Low birth weight    | 119 (11.3%)   | 2.6 (0.5 to 4.6)         | 1.44 (1.11–1.86) |\n+-------------------+---------------------+---------------+--------------------------+------------------+\n| Middle childhood\\ | Normal birth weight | 1527 (10.0%)  | Reference                | 1.00             |\n| (6-12 years)      |                     |               |                          |                  |\n+-------------------+---------------------+---------------+--------------------------+------------------+\n|                   | Low birth weight    | 241 (15.9%)   | 1.8 (−0.1 to 3.8)        | 1.21 (1.00–1.45) |\n+-------------------+---------------------+---------------+--------------------------+------------------+\n| Teenager\\         | Normal birth weight | 1967 (14.3%)  | Reference                | 1.00             |\n| (13-17 years)     |                     |               |                          |                  |\n+-------------------+---------------------+---------------+--------------------------+------------------+\n|                   | Low birth weight    | 263 (19.7%)   | 1.1 (−1.1 to 3.4)        | 1.09 (0.92–1.30) |\n+-------------------+---------------------+---------------+--------------------------+------------------+\n\n~Adjusted results estimated using logistic regression, run separately within each age stratum, adjusted for sex, race/ethnicity, preterm birth, familial poverty ratio, education level of adults, insurance type, and household smoker status~\n\n***Table 3 Notes:***\n\n- *Only **preschool (3-5)** is significant on both scales (prevalence diff CI excludes 0, OR CI excludes 1).*\n- ***Middle childhood (6-12)** is borderline on both (OR lower bound = 1.00, prevalence diff lower bound = −0.1).*\n- ***Toddlers** and **teens** are non-significant.*\n- *The overall pattern: the low-birth-weight/asthma association is strongest in early childhood and fades with age.*\n\n------------------------------------------------------------------------\n\n## Age-Stratified Models (Table 3)\n\n### Infants to Toddlers (0-2 years) Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Toddlers (0-2 years)\n\n# fit the asthma model for infants to toddlers\nmodel_toddler <- glm(asthma ~ birth_weight_low + sex + race + born_early \n                     + poverty + education + insurance_type + cigarettes,\n                     data = filter(df, age_cats == \"Infants/Toddlers (0-2)\"),\n                     family = binomial)\n\n# pull the odds ratio + CI for low birth weight\ntidy(model_toddler, exponentiate = TRUE, conf.int = TRUE) |>\n  filter(str_detect(term, \"birth_weight_low\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  term                estimate std.error statistic p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 birth_weight_lowYes     1.37     0.231      1.36   0.174    0.863      2.14\n```\n\n\n:::\n\n```{.r .cell-code}\n# checks how many kids the model used\nnobs(model_toddler)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8788\n```\n\n\n:::\n\n```{.r .cell-code}\n# predicted asthma probability, No vs Yes\npred_toddler <- predictions(model_toddler,\n                            newdata = datagrid(\n                              birth_weight_low = c(\"No\", \"Yes\")))\n\n# check if the two predictions differ\nhypotheses(pred_toddler, hypothesis = \"b1 = b2\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Hypothesis Estimate Std. Error       z Pr(>|z|)   S  2.5 % 97.5 %\n      b1=b2 -0.00827      0.231 -0.0358    0.971 0.0 -0.461  0.445\n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\n- *Toddlers (0-2): the birth weight association is not significant in this age group. OR = 1.37 (95% CI: 0.86–2.14, p = 0.17) — the CI crosses 1.*\n- *Sample size: 8,788 toddlers.*\n- *Interpretation: among toddlers, low birth weight shows no statistically significant association with asthma on either scale. The OR points in the same direction as the overall analysis but is imprecise, likely because asthma is rarer and less established at this age (fewer cases to detect an effect).*\n\n### Preschoolers (3-5 years) Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preschool (3-5 years)\n\n# fit the asthma model for preschoolers\nmodel_prek <- glm(asthma ~ birth_weight_low + sex + race + born_early +\n                    poverty + education + insurance_type + cigarettes,\n                  data = filter(df, age_cats == \"Preschool (3-5)\"),\n                  family = binomial)\n\n# pull the odds ratio + CI for low birth weight\ntidy(model_prek, exponentiate = TRUE, conf.int = TRUE) |>\n  filter(str_detect(term, \"birth_weight_low\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  term                estimate std.error statistic p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 birth_weight_lowYes     1.44     0.132      2.75 0.00598     1.11      1.86\n```\n\n\n:::\n\n```{.r .cell-code}\n# Checks how many kids did the model use\nnobs(model_prek)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11115\n```\n\n\n:::\n\n```{.r .cell-code}\n# Predicted asthma probability, No vs Yes\npred_prek <- predictions(model_prek,\n                         newdata = datagrid(\n                           birth_weight_low = c(\"No\", \"Yes\")))\n\n# Checks if the two predictions differ\nhypotheses(pred_prek, hypothesis = \"b1 = b2\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Hypothesis Estimate Std. Error      z Pr(>|z|)   S  2.5 % 97.5 %\n      b1=b2  -0.0281      0.132 -0.212    0.832 0.3 -0.287  0.231\n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\n- *Preschool (3-5): the birth weight association is significant here. OR = 1.44 (95% CI: 1.11–1.86, p = 0.006) — CI excludes 1.*\n- *Same direction as the overall analysis (reference = low birth weight, so not-low-birth-weight kids have higher odds).*\n- *Sample size: 11,115 preschoolers.*\n- *Interpretation: among preschoolers, low birth weight is significantly associated with asthma on the relative (odds) scale, unlike toddlers where it wasn't. The absolute difference remains modest.*\n\n### Middle Childhood (6-12 years) Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Middle childhood (6-12)\n\n# fit the asthma model for middle childhood\nmodel_middle <- glm(asthma ~ birth_weight_low + sex + race + born_early +\n                      poverty + education + insurance_type + cigarettes,\n                    data = filter(df, age_cats == \"Middle childhood (6-12)\"),\n                    family = binomial)\n\n# pull the odds ratio + CI for low birth weight\ntidy(model_middle, exponentiate = TRUE, conf.int = TRUE) |>\n  filter(str_detect(term, \"birth_weight_low\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  term                estimate std.error statistic p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 birth_weight_lowYes     1.21    0.0961      1.95  0.0510    0.998      1.45\n```\n\n\n:::\n\n```{.r .cell-code}\n# checks how many kids did the model use\nnobs(model_middle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16280\n```\n\n\n:::\n\n```{.r .cell-code}\n# Predicted asthma probability, No vs Yes\npred_middle <- predictions(model_middle,\n                           newdata = datagrid(\n                             birth_weight_low = c(\"No\", \"Yes\")))\n\n# # check if the two predictions differ\nhypotheses(pred_middle, hypothesis = \"b1 = b2\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Hypothesis Estimate Std. Error      z Pr(>|z|)   S  2.5 % 97.5 %\n      b1=b2  -0.0166     0.0961 -0.173    0.863 0.2 -0.205  0.172\n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\n- *Middle childhood (6-12): the birth weight association is borderline — just misses significance. OR = 1.21 (95% CI: 0.998–1.45, p = 0.051). The CI barely touches 1.*\n- *Largest subsample: 16,280 kids.*\n- *Interpretation: among middle-childhood kids, low birth weight shows a suggestive but not quite statistically significant association with asthma (p right at 0.05, CI's lower bound essentially at 1). The effect size (OR 1.21) matches the overall fully-adjusted estimate, so it's consistent in direction and magnitude — just short of the significance threshold in this subgroup.*\n\n### Teenagers (13-17 years) Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Teenagers (13-17)\n\n# Fit the asthma model for teens\nmodel_teens <- glm(asthma ~ birth_weight_low + sex + race + born_early +\n                      poverty + education + insurance_type + cigarettes,\n                    data = filter(df, age_cats == \"Teenagers (13-17)\"), \n                    family = binomial)\n\n# Pull the odds ratio + CI for low birth weight\ntidy(model_teens, exponentiate = TRUE, conf.int = TRUE) |>\n  filter(str_detect(term, \"birth_weight_low\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  term                estimate std.error statistic p.value conf.low conf.high\n  <chr>                  <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 birth_weight_lowYes     1.09    0.0886      1.00   0.317    0.917      1.30\n```\n\n\n:::\n\n```{.r .cell-code}\n# Checks how many teens the model used\nnobs(model_teens)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14397\n```\n\n\n:::\n\n```{.r .cell-code}\n# Predicted asthma probability, No vs Yes\npred_teens <- predictions(model_teens,\n                           newdata = datagrid(\n                             birth_weight_low = c(\"No\", \"Yes\")))\n\n# Checks if the two predictions differ\nhypotheses(pred_teens, hypothesis = \"b1 = b2\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Hypothesis Estimate Std. Error      z Pr(>|z|)   S  2.5 % 97.5 %\n      b1=b2  -0.0105     0.0886 -0.118    0.906 0.1 -0.184  0.163\n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\n- *Teenagers (13-17): the birth weight association is not significant. OR = 1.09 (95% CI: 0.92–1.30, p = 0.32) — CI crosses 1.*\n- *Sample size: 14,397 teens.*\n- *Interpretation: among teenagers, low birth weight shows no significant association with asthma on either scale. This is the weakest effect of all age groups (OR closest to 1), suggesting any early birth-weight association has largely faded by adolescence.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Information for filling out Table 3\n\n# Gives the covariate-adjusted prevalence difference on the probability scale.\navg_comparisons(model_toddler, variables = \"birth_weight_low\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S    2.5 % 97.5 %\n  0.00849    0.00695 1.22    0.222 2.2 -0.00513 0.0221\n\nTerm: birth_weight_low\nType: response\nComparison: Yes - No\n```\n\n\n:::\n\n```{.r .cell-code}\navg_comparisons(model_prek,    variables = \"birth_weight_low\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S   2.5 % 97.5 %\n   0.0256     0.0105 2.45   0.0142 6.1 0.00516 0.0461\n\nTerm: birth_weight_low\nType: response\nComparison: Yes - No\n```\n\n\n:::\n\n```{.r .cell-code}\navg_comparisons(model_middle,  variables = \"birth_weight_low\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S    2.5 % 97.5 %\n   0.0182    0.00987 1.85   0.0648 3.9 -0.00112 0.0376\n\nTerm: birth_weight_low\nType: response\nComparison: Yes - No\n```\n\n\n:::\n\n```{.r .cell-code}\navg_comparisons(model_teens,   variables = \"birth_weight_low\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error     z Pr(>|z|)   S   2.5 % 97.5 %\n   0.0112     0.0115 0.977    0.329 1.6 -0.0113 0.0337\n\nTerm: birth_weight_low\nType: response\nComparison: Yes - No\n```\n\n\n:::\n:::\n\n\n**Interpretation**\n\n- *These are the covariate-adjusted absolute differences (low vs normal birth weight) within each age stratum, and they populate the prevalence-difference column of Table 3.*\n\n- *Only preschool (3–5) reaches significance (2.6 pp, 95% CI 0.5–4.6). Toddlers (0.8 pp), middle childhood (1.8 pp), and teenagers (1.1 pp) all have confidence intervals that cross zero.*\n\n- *The pattern mirrors the odds ratios: the absolute effect of low birth weight on asthma risk is largest in early childhood and diminishes with age.*\n\n------------------------------------------------------------------------\n\n# Results\n\n**TO BE COMPLETED**\n\n------------------------------------------------------------------------\n\n# Conclusions\n\n**TO BE COMPLETED**\n\n------------------------------------------------------------------------\n\n# Appendix\n\n## Forest Plot: Odds Ratios Across Models\n\nThis appendix figure presents a forest plot summarizing the birth-weight odds ratios across the three overall models. Plotting the unadjusted, age-adjusted, and fully adjusted estimates together on a single axis, with a reference line at an odds ratio of 1, provides a visual summary of how the association attenuated as covariates were added. It presents the same results reported in Table 2 in graphical form.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrat <- bind_rows(\n  tidy(model_toddler, exponentiate = TRUE, conf.int = TRUE) |> mutate(age_group = \"Toddler (0-2)\"),\n  tidy(model_prek,    exponentiate = TRUE, conf.int = TRUE) |> mutate(age_group = \"Preschool (3-5)\"),\n  tidy(model_middle,  exponentiate = TRUE, conf.int = TRUE) |> mutate(age_group = \"Middle childhood (6-12)\"),\n  tidy(model_teens,   exponentiate = TRUE, conf.int = TRUE) |> mutate(age_group = \"Teenager (13-17)\")\n) |>\n  filter(str_detect(term, \"birth_weight_low\")) |>\n  mutate(age_group = factor(age_group,\n                            levels = c(\"Teenager (13-17)\", \"Middle childhood (6-12)\",\n                                       \"Preschool (3-5)\", \"Toddler (0-2)\")))\n\nggplot(strat, aes(x = estimate, y = age_group)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"gray50\") +\n  geom_pointrange(aes(xmin = conf.low, xmax = conf.high)) +\n  labs(title = \"Low Birth Weight and Asthma Odds by Age Group\",\n       subtitle = \"Association is strongest in early childhood and fades with age\",\n       x = \"Odds ratio (95% CI)\", y = NULL,\n       caption = \"Each age stratum adjusted separately. Data from 2023 NSCH\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 11,\n                              face = \"bold\",\n                              hjust = 0.5),\n    plot.subtitle = element_text(size = 9, hjust = 0.5),\n    axis.title.x = element_text(margin = margin(t = 10), size = 9),\n    axis.title.y = element_text(margin = margin(r = 10), size = 9),\n    plot.caption = element_text(\n      size = 8,\n      color = \"darkgray\",\n      margin = margin(t = 15, b = 10, unit = \"pt\")\n    ))\n```\n\n::: {.cell-output-display}\n![Odds ratios for low birth weight across the three overall models.](02_epi690a_final_project_ANALYSIS_files/figure-html/fig-forest-appendix-1.png){#fig-forest-appendix width=576}\n:::\n:::\n\n",
    "supporting": [
      "02_epi690a_final_project_ANALYSIS_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"02_epi690a_final_project_ANALYSIS_files/libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"02_epi690a_final_project_ANALYSIS_files/libs/jquery-1.11.3/jquery.min.js\"></script>\n<link href=\"02_epi690a_final_project_ANALYSIS_files/libs/jquery-sparkline-2.1.2/jquery.sparkline.css\" rel=\"stylesheet\" />\n<script src=\"02_epi690a_final_project_ANALYSIS_files/libs/jquery-sparkline-2.1.2/jquery.sparkline.js\"></script>\n<script src=\"02_epi690a_final_project_ANALYSIS_files/libs/sparkline-binding-2.0/sparkline.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}