{
  "hash": "316b7f843f6c14e15ed0f9f71b6ebc16",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Among U.S. children aged 0–17, is low birth weight associated with increased odds of an ever asthma diagnosis, after adjusting for child age, sex, race/ethnicity, household income, and secondhand smoke exposure?\"\nauthor:\n  - name: Javier Diaz Collante, Rachel Huselid, Anjelica Martinez\n    email: anjelicamart@umass.edu\n    affiliation: Department of Biostatistics & Epidemiology\n  - name: \"Created on: June 28, 2026\"\nauthor-title: \"Author\"\naffiliation-title: \"University of Massachusetts - Amherst\"\nabstract-title: Purpose\nabstract: This notebook is the data management (data prep and cleaning) for our EPI 690A final project. \npublished-title: \"Date Updated\"\nformat:\n  html:\n    embed-resources: true\n    anchor-sections: true\n    code-fold: show\n    code-tools: true\n    fig-width: 6\n    fig-height: 4\n    code-block-bg: \"#f1f3f5\"\n    code-block-border-left: \"#31BAE9\"\n    mainfont: Source Sans Pro\n    theme: journal\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    captions: true\n    table-captions: true\n---\n\n# Setup\n\nLoad relevant packages and setup code to help with HTML rendering.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Packages\"}\n# Packages Used\n \npacman::p_load(\n    dplyr,        # data manipulation\n    forcats,      # tools for working with categorical variables\n    here,         # file paths relative to R project root folder\n    rio,          # import/export of many types of data \n    tidyverse,    # includes many packages for tidy data wrangling \n    Hmisc,        # includes many functions in Harrellverse \n    data.table,   # (alternative) faster than tidyverse\n    qreport,      # useful for formatting in quarto\n    sparkline,    # inline interactive plots\n    lubridate,    # simplifies working with dates\n    janitor,      # tables and data cleaning\n    skimr,        # summary statistics\n    gtsummary,    # making descriptive and statistical tables\n    rstatix,      # quickly run statistical tests and summaries\n    labelled,     # labels variables\n    naniar,        # assessing missing data\n    datadictionary, # creates data dictionaries\n    haven\n\n )\n \noptions(scipen = 999) # removes scientific notation\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Setup\"}\n# Source: Frank Harrell https://hbiostat.org/rflow/ \n# Make base graphics look better:\nspar <- function(bot=0, left=0, top=0, rt=0)\n  par(mar=c(3.25 + bot, 5 + left, 0.5 + top, 0.5 * rt),\n      lwd=1.75, mgp=c(2.0, 0.475, 0), tcl=-0.4, xpd=FALSE, ps=14,\n      cex.lab=1.15, cex.axis=0.8)\n\n# Set abbreviations for chunk option names\nknitr::set_alias(w = 'fig.width', h = 'fig.height')\n\noptions(prType='html')   # for certain Hmisc and rms functions\n\n# To automatically sense which output format is being created and \n# create a character string that will work for both `html` and `LaTeX`.  \n# For `LaTeX`, a boxed note in the body of the document will appear.\n\nishtml <- knitr::is_html_output()\nmNote  <- if(ishtml) '.column-margin' else '.callout-note appearance=\"minimal\"'\n\n#FHarrell: \"Note that to initialize javascript jQuery dependencies \n# we must include sparkline::sparkline(0) somewhere in the report \n# before creating the first sparkline output.\"\nsparkline::sparkline(0)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<span id=\"htmlwidget-3b0ff8b10c4f9c870246\" class=\"sparkline html-widget\"></span>\n<script type=\"application/json\" data-for=\"htmlwidget-3b0ff8b10c4f9c870246\">{\"x\":{\"values\":0,\"options\":{\"height\":20,\"width\":60},\"width\":60,\"height\":20},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n# Codebook\n\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n|                      |                       |                                                            |                                                                                                          |\n+======================+=======================+============================================================+==========================================================================================================+\n| **New Variable**     | **Original Variable** | **Label**                                                  | **Values**                                                                                               |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| age                  | SC_AGE_YEARS          | Age of selected child (years)                              |                                                                                                          |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| sex                  | SC_SEX                | Sex of selected child                                      | 1 = Male                                                                                                 |\n|                      |                       |                                                            |                                                                                                          |\n|                      |                       |                                                            | 2 = Female                                                                                               |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| race                 | SC_RACE_R             | Race of selected child (detailed)                          | 1 = White alone                                                                                          |\n|                      |                       |                                                            |                                                                                                          |\n|                      |                       |                                                            | 2 = Black or African American alone                                                                      |\n|                      |                       |                                                            |                                                                                                          |\n|                      |                       |                                                            | 3 = American Indian or Alaska Native alone                                                               |\n|                      |                       |                                                            |                                                                                                          |\n|                      |                       |                                                            | 4 = Asian alone                                                                                          |\n|                      |                       |                                                            |                                                                                                          |\n|                      |                       |                                                            | 5 = Native Hawaiian and Other Pacific Islander alone                                                     |\n|                      |                       |                                                            |                                                                                                          |\n|                      |                       |                                                            | 7 = Two or More Races                                                                                    |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| hispanic             | SC_HISPANIC_R         | Hispanic origin of selected child (groups)                 | 1 = Hispanic or Latino Origin                                                                            |\n|                      |                       |                                                            |                                                                                                          |\n|                      |                       |                                                            | 2 = Not Hispanic or Latino Origin                                                                        |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| birth_weight_ver_low | BIRTHWT_VL            | Birth weight is very low (\\<1500g)                         | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| birth_weight_low     | BIRTHWT_L             | Birth weight is low (\\<2500g)                              | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| asthma               | K2Q40A                | Ever diagnosed with asthma                                 | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| born_early           | K2Q05                 | Born 3 or more weeks before due date                       | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| breastfed            | K6Q40                 | Ever breastfed                                             | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| poverty              | FPL_I1                | Family poverty ratio, first implicate                      | 50 or less - 400 or more                                                                                 |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| education            | HIGRADE_TVIS          | Highest level of education among reported adults, Detailed | 1 = Less than high school\\                                                                               |\n|                      |                       |                                                            | 2 = High school (including vocational, trade, or business school)\\                                       |\n|                      |                       |                                                            | 3 = Some college or Associate Degree\\                                                                    |\n|                      |                       |                                                            | 4 = College degree or higher                                                                             |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| insurance_type       | INSTYPE               | Insurance type                                             | 1 = Public only (government assistance)\\                                                                 |\n|                      |                       |                                                            | 2 = Private only (privately purchased, including through ACA marketplace, through employer, or TRICARE)\\ |\n|                      |                       |                                                            | 3 = Private and public\\                                                                                  |\n|                      |                       |                                                            | 5 = Not insured                                                                                          |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| cigarettes           | K9Q40                 | Anyone in household use cigarettes                         | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| smoke_inside         | K9Q41                 | Anyone smoke inside of home                                | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| vape                 | VAPE                  | Vape/E-Cigarettes inside of home                           | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n| allergies            | ALLERGIES             | Ever diagnosed with allergies                              | 1 = Yes\\                                                                                                 |\n|                      |                       |                                                            | 2 = No                                                                                                   |\n+----------------------+-----------------------+------------------------------------------------------------+----------------------------------------------------------------------------------------------------------+\n\n~Codebook provided by National Survey of Children's Health~\n\n# Load Data\n\nData was collected from the canvas website and originally created by the NCSH.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import data\ndf_raw <- import(here(\"data\", \"raw\", \"nsch2023data.sas7bdat\"))\n\n# Review data structure\nhead(df_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  HEIGHT FIPSST STRATUM     HHID FORMTYPE TOTKIDS_R TENURE HHLANGUAGE\n1     NA     06       1 23043707       T2         1      3          1\n2 149.86     06       1 23120547       T3         2      1          1\n3 157.47     06       1 23197456       T3         1      1          2\n4 157.47     06       1 23197458       T3         2      1          1\n5 149.86     06       1 23235909       T2         2      3          1\n6 165.10     06       1 23082205       T3         4      2          2\n  SC_AGE_YEARS SC_SEX K2Q35A_1_YEARS BIRTH_MO BIRTH_YR K6Q41R_STILL\n1           11      1             NA        8     2011           NA\n2           14      2             NA        2     2009           NA\n3           17      2             NA        3     2006           NA\n4           12      2             NA        8     2010           NA\n5           10      2             NA        7     2012           NA\n6           14      2             NA       12     2008           NA\n  K6Q42R_NEVER K6Q43R_NEVER K6Q13A K6Q13B K6Q14A K6Q14B EYECARE1 EYECARE2\n1           NA           NA     NA     NA     NA     NA       NA       NA\n2           NA           NA     NA     NA     NA     NA        1        2\n3           NA           NA     NA     NA     NA     NA       NA       NA\n4           NA           NA     NA     NA     NA     NA        1        1\n5           NA           NA     NA     NA     NA     NA        1        1\n6           NA           NA     NA     NA     NA     NA       NA       NA\n  EYECARE3 EYECARE4 K4Q30_R_1 K4Q30_R_2 K4Q30_R_3 DENTALSERV1 DENTALSERV2\n1       NA       NA         1         2         2           1           1\n2        2        2         1         2         2           1           1\n3       NA       NA         1         2         2           1           1\n4        2        2         1         2         2           1           1\n5        2        1         2         1         2           1           1\n6       NA       NA         1         2         2           1           1\n  DENTALSERV3 DENTALSERV4 DENTALSERV5 DENTALSERV6 DENTALSERV7 K4Q28X01 K4Q28X02\n1           1           1           1           1           2       NA       NA\n2           1           1           1           2           2       NA       NA\n3           1           1           1           1           2       NA       NA\n4           1           1           1           2           2       NA       NA\n5           1           2           1           2           2       NA       NA\n6           2           1           2           2           2       NA       NA\n  K4Q28X03 K4Q28X_EAR K4Q28X04 K4Q28X05 SESPLANYR SESPLANMO K4Q37 SPCSERVMO\n1       NA         NA       NA       NA        NA        NA    NA        NA\n2       NA         NA       NA       NA        NA        NA    NA        NA\n3       NA         NA       NA       NA        NA        NA    NA        NA\n4       NA         NA       NA       NA        NA        NA    NA        NA\n5       NA         NA       NA       NA        NA        NA    NA        NA\n6       NA         NA       NA       NA        NA        NA    NA        NA\n  LIVEUSA_YR LIVEUSA_MO K11Q43R PLACESLIVED A1_AGE A2_AGE HHCOUNT FAMCOUNT\n1         NA         NA       2           1     49     NA       3        3\n2         NA         NA       1           1     38     43       4        4\n3         NA         NA       0           1     54     64       5        5\n4         NA         NA       1           1     44     49       4        4\n5         NA         NA       2           1     31     30       4        4\n6         NA         NA       1           1     42     41       6        6\n  BREATHING SWALLOWING STOMACH PHYSICALPAIN HANDS COORDINATION TOOTHACHES\n1         1          2       2            2    NA           NA          2\n2         2          2       2            2    NA           NA          2\n3         2          2       2            2    NA           NA          2\n4         2          2       2            2    NA           NA          2\n5         2          2       2            2    NA           NA          2\n6         2          2       2            2    NA           NA          2\n  GUMBLEED CAVITIES MEMORYCOND WALKSTAIRS DRESSING ERRANDALONE K2Q43B BLINDNESS\n1        2        2          2          2        2          NA      2         2\n2        2        2          2          2        2           2      2         2\n3        2        2          2          2        2           2      2         2\n4        2        2          2          2        2           2      2         2\n5        2        2          2          2        2          NA      2         2\n6        2        1          2          2        2           2      2         2\n  ALLERGIES ALLERGIES_CURR K2Q40A K2Q40B AUTOIMMUNE K2Q61A DIABETES\n1         1              1      1      1          2      2        2\n2         2             NA      2     NA          2      2        2\n3         2             NA      2     NA          2      2        2\n4         2             NA      2     NA          2      2        2\n5         2             NA      2     NA          2      2        2\n6         2             NA      2     NA          2      2        2\n  DIABETES_CURR K2Q42A K2Q42B HEART HEART_BORN HEART_CURR HEADACHE\n1            NA      2     NA     2         NA         NA        2\n2            NA      2     NA     2         NA         NA        2\n3            NA      2     NA     2         NA         NA        2\n4            NA      2     NA     2         NA         NA        2\n5            NA      2     NA     2         NA         NA        2\n6            NA      2     NA     2         NA         NA        1\n  HEADACHE_CURR K2Q38A K2Q38B K2Q33A K2Q33B K2Q32A K2Q32B DOWNSYN BLOOD\n1            NA      2     NA      2     NA      2     NA       2     2\n2            NA      2     NA      2     NA      2     NA       2     2\n3            NA      2     NA      2     NA      2     NA       2     2\n4            NA      2     NA      2     NA      2     NA       2     2\n5            NA      2     NA      2     NA      2     NA       2     2\n6             1      2     NA      2     NA      2     NA       2     2\n  SICKLECELL THALASSEMIA HEMOPHILIA BLOOD_OTHER BLOOD_SCREEN CYSTFIB\n1         NA          NA         NA          NA           NA       2\n2         NA          NA         NA          NA           NA       2\n3         NA          NA         NA          NA           NA       2\n4         NA          NA         NA          NA           NA       2\n5         NA          NA         NA          NA           NA       2\n6         NA          NA         NA          NA           NA       2\n  CYSTFIB_SCREEN FASD K2Q34A K2Q34B K2Q36A K2Q36B K2Q60A K2Q60B K2Q37A K2Q37B\n1             NA    2      2     NA      2     NA      2     NA      2     NA\n2             NA    2      2     NA      2     NA      2     NA      2     NA\n3             NA    2      2     NA      2     NA      2     NA      2     NA\n4             NA    2      2     NA      2     NA      2     NA      2     NA\n5             NA    2      2     NA      2     NA      2     NA      2     NA\n6             NA    2      2     NA      2     NA      2     NA      2     NA\n  K2Q30A K2Q30B K2Q35A K2Q35B AUTISMMED AUTISMTREAT K2Q31A K2Q31B K2Q31D\n1      2     NA      2     NA        NA          NA      2     NA     NA\n2      2     NA      2     NA        NA          NA      2     NA     NA\n3     NA     NA      2     NA        NA          NA      2     NA     NA\n4      2     NA      2     NA        NA          NA      2     NA     NA\n5      2     NA      2     NA        NA          NA      2     NA     NA\n6      2     NA      2     NA        NA          NA      2     NA     NA\n  ADDTREAT CONCUSSION SEEKCARE CONFIRMINJURY K2Q05 K6Q40 S4Q01 DOCPRIVATE\n1       NA          2       NA            NA     2    NA     1         NA\n2       NA          2       NA            NA     2    NA     1          2\n3       NA          2       NA            NA     2    NA     1          1\n4       NA          2       NA            NA     2    NA     2         NA\n5       NA          2       NA            NA     2    NA     2         NA\n6       NA          2       NA            NA     2    NA     1          2\n  OVERWEIGHT K6Q10 K6Q12 ENGAGE_FAST ENGAGE_INTEREST ENGAGE_PICKY ENGAGE_BINGE\n1          2    NA    NA           1               1            1            2\n2          2    NA    NA           2               2            2            2\n3          2    NA    NA           1               2            2            2\n4          2    NA    NA           2               2            2            2\n5          2    NA    NA           1               1            1            1\n6          2    NA    NA           2               2            2            2\n  ENGAGE_PURG ENGAGE_PILLS ENGAGE_EXERCISE ENGAGE_NOEAT K4Q01 USUALGO USUALSICK\n1           2            2               2            2     2       1         1\n2           2            2               2            2     1       1         1\n3           2            2               2            2     1       1         1\n4           2            2               2            2     1       1         1\n5           2            2               2            2     2       2        NA\n6           2            2               2            2     2       1         1\n  VISIONSCREENOTHER VISIONEXAMREC EYEDOCTOR K4Q23 K4Q27 NOTELIG AVAILABLE\n1                 1             1         2     2     2      NA        NA\n2                 1             2         1     2     2      NA        NA\n3                 1             2         2    NA     2      NA        NA\n4                 1             2         1     2     2      NA        NA\n5                 1             1         1     2     2      NA        NA\n6                 2            NA         2     2     2      NA        NA\n  APPOINTMENT TRANSPORTCC NOTOPEN ISSUECOST HOSPITALSTAY K6Q15 SESCURRSVC K4Q36\n1          NA          NA      NA        NA            2     2         NA     2\n2          NA          NA      NA        NA            2     2         NA     2\n3          NA          NA      NA        NA            1     2         NA     2\n4          NA          NA      NA        NA            2     2         NA     2\n5          NA          NA      NA        NA            2     2         NA     2\n6          NA          NA      NA        NA            2     2         NA     2\n  K4Q38 K5Q10 DECISIONS_R K5Q21 TREATCHILD TREATADULT MEDHISTORY WRITEPLAN\n1    NA     2           2    NA         NA         NA         NA        NA\n2    NA     2           1     1          1          2          1         2\n3    NA     2           1     2          1          2          1         2\n4    NA     2          NA    NA          1          2          1         2\n5    NA     2          NA    NA         NA         NA         NA        NA\n6    NA     2           2    NA          2         NA          1         2\n  RECEIVECOPY HEALTHKNOW KEEPINSADULT CURRCOV K12Q03 K12Q04 K12Q12 TRICARE\n1          NA         NA           NA       1      2      2      1       2\n2          NA          2            2       1      1      2      2       2\n3          NA          2            1       1      2      2      1       2\n4          NA          1           NA       1      1      2      2       2\n5          NA         NA           NA       1      2      2      1       2\n6          NA          1           NA       1      2      2      1       2\n  K11Q03R HCCOVOTH K3Q25 STOPWORK CUTHOURS AVOIDCHG ONEWORD TWOWORDS THREEWORDS\n1       2        2    NA        2        2        2      NA       NA         NA\n2       2        2     2        2        2        2      NA       NA         NA\n3       2        2    NA        2        2        2      NA       NA         NA\n4       2        2    NA        2        2        2      NA       NA         NA\n5       2        2     2        2        2        2      NA       NA         NA\n6       2        2    NA        2        2        2      NA       NA         NA\n  ASKQUESTION ASKQUESTION2 TELLSTORY UNDERSTAND DIRECTIONS POINT DIRECTIONS2\n1          NA           NA        NA         NA         NA    NA          NA\n2          NA           NA        NA         NA         NA    NA          NA\n3          NA           NA        NA         NA         NA    NA          NA\n4          NA           NA        NA         NA         NA    NA          NA\n5          NA           NA        NA         NA         NA    NA          NA\n6          NA           NA        NA         NA         NA    NA          NA\n  UNDERSTAND2 REPEATED K7Q30 K7Q31 K7Q32 K7Q37 K7Q38 BORNUSA K8Q35 K6Q27 K9Q40\n1          NA        2     1     2     2     2     2       1     1    NA     1\n2          NA        2     1     1     1     2     2       1     1    NA     2\n3          NA        2     1     2     2     1     2       1     2    NA     2\n4          NA        2     2     1     2     1     2       1     1    NA     2\n5          NA        2     2     1     1     2     2       1     2    NA     2\n6          NA        2     2     1     2     2     1       1     2    NA     2\n  K9Q41 VAPE K11Q60 K11Q61 K11Q62 EBTCARDS S9Q34 SSI SSIDISABILITY K10Q11\n1    NA    1      2      1      1        2     2   2            NA      1\n2    NA    2      2      2      1        2     2   2            NA      1\n3    NA    2     NA     NA      1       NA    NA   2            NA      1\n4    NA    2      2      2      1        2     2   2            NA      1\n5    NA    2      2      1      1        1     2   2            NA      1\n6    NA   NA     NA     NA      1        1     1  NA            NA      1\n  K10Q12 K10Q13 K10Q14 K10Q20 K10Q22 K10Q23 K9Q96 ACE3 ACE4 ACE5 ACE6 ACE7 ACE8\n1      1      1      1      1      1      1     1    1    2    1    1    2    2\n2      1      1      1      2      2      2     1    2    2    2    2    2    2\n3      2      1      1      1      2      1     1    2    2    2    2    2    2\n4      2      2      2      2      2      2     1    2    2    2    2    2    2\n5      1      2      2      2      2      2     2    2    2    2    2    2    2\n6      1      2      2      2      2      2     2    2    2    2    2    2    2\n  ACE9 ACE10 ACE12 ACE11 VIDEOPHONE A1_DEPLSTAT A2_DEPLSTAT ALLERGIES_DESC\n1    2     2     2     2          2          NA          NA              2\n2    2     2     2     2          1          NA          NA             NA\n3    2     2     2     2          1          NA          NA             NA\n4    2     2     2     2          2          NA          NA             NA\n5    2     2     2     2          2          NA          NA             NA\n6    2     2     2     2          2          NA          NA             NA\n  K2Q40C AUTOIMMUNE_DESC CERPALS_DESC DIABETES_DESC K2Q42C HEART_DESC\n1      2              NA           NA            NA     NA         NA\n2     NA              NA           NA            NA     NA         NA\n3     NA              NA           NA            NA     NA         NA\n4     NA              NA           NA            NA     NA         NA\n5     NA              NA           NA            NA     NA         NA\n6     NA              NA           NA            NA     NA         NA\n  HEADACHE_DESC K2Q38C K2Q33C K2Q32C BLOOD_DESC K2Q34C K2Q36C K2Q60C K2Q37C\n1            NA     NA     NA     NA         NA     NA     NA     NA     NA\n2            NA     NA     NA     NA         NA     NA     NA     NA     NA\n3            NA     NA     NA     NA         NA     NA     NA     NA     NA\n4            NA     NA     NA     NA         NA     NA     NA     NA     NA\n5            NA     NA     NA     NA         NA     NA     NA     NA     NA\n6             1     NA     NA     NA         NA     NA     NA     NA     NA\n  K2Q30C K2Q35C K2Q31C ENGAGECONCERN BODYIMAGE BOUNCEABALL DRAWACIRCLE\n1     NA     NA     NA             3         3          NA          NA\n2     NA     NA     NA            NA         3          NA          NA\n3     NA     NA     NA            NA        NA          NA          NA\n4     NA     NA     NA            NA         3          NA          NA\n5     NA     NA     NA             2         3          NA          NA\n6     NA     NA     NA            NA         3          NA          NA\n  DRAWAFACE DRAWAPERSON A1_SEX A1_BORN A1_EMPLOYED_R A1_GRADE A1_MARITAL\n1        NA          NA      2       1             1        5          4\n2        NA          NA      2       2             1        8          1\n3        NA          NA      2       2             2        3          1\n4        NA          NA      2       1             1        6          1\n5        NA          NA      2       1             5        4          2\n6        NA          NA      2       2             5        7          1\n  A1_RELATION A2_SEX A2_BORN A2_EMPLOYED_R A2_GRADE A2_MARITAL A2_RELATION\n1           1     NA      NA            NA       NA         NA           8\n2           1      1       2             2        6          1           1\n3           1      1       2            NA       NA          1           1\n4           1      1       2             1        1          1           1\n5           1      1       1             1        4          2           1\n6           1      1       1             1        3          1           1\n  A1_ACTIVE A2_ACTIVE A1_PHYSHEALTH A1_MENTHEALTH A2_PHYSHEALTH A2_MENTHEALTH\n1         1        NA             3             3            NA            NA\n2         1         1             3             1             3             2\n3         1         1             3             3             3             3\n4         1         1             1             1             2             2\n5         1         1             3             3             2             1\n6         1         1             1             2             2             1\n  K2Q01 K2Q01_D K5Q40 K5Q41 K5Q42 K5Q43 K5Q44 DISCUSSOPT RAISECONC BESTFORCHILD\n1     2       3     1     1     1     1     1         NA        NA           NA\n2     2       1     2     2     3     1     3          1         1            1\n3     3       3     3     2     2     2     3         NA        NA           NA\n4     1       1    NA    NA    NA    NA    NA         NA        NA           NA\n5     1       5    NA    NA    NA    NA    NA         NA        NA           NA\n6     1       2     1     1     3     3     2         NA        NA           NA\n  K3Q20 K3Q22 K3Q21B K6Q70_R K6Q73_R K6Q71_R K6Q72_R K7Q84_R K7Q85_R K7Q82_R\n1     1     1     NA      NA      NA       2      NA       3       2       2\n2     1     1      2      NA      NA       2      NA       2       2       1\n3     1     1     NA      NA      NA       2      NA       2       2       2\n4     1     1     NA      NA      NA       1      NA       1       2       1\n5     3     3      1      NA      NA       1      NA       1       1       1\n6     1     1     NA      NA      NA       1      NA       1       1       1\n  K7Q83_R K7Q70_R BULLIED_R BULLY RECOGBEGIN SAMESOUND CLEAREXP WRITENAME\n1       2       4         1     1         NA        NA       NA        NA\n2       1       3         1     1         NA        NA       NA        NA\n3       2       2        NA    NA         NA        NA       NA        NA\n4       1       4         2     1         NA        NA       NA        NA\n5       1       1         5     2         NA        NA       NA        NA\n6       1       4         1     1         NA        NA       NA        NA\n  FOCUSON READONEDIGIT SIMPLEADDITION GROUPOFOBJECTS NAMEEMOTIONS STARTNEWACT\n1      NA           NA             NA             NA           NA          NA\n2      NA           NA             NA             NA           NA          NA\n3      NA           NA             NA             NA           NA          NA\n4      NA           NA             NA             NA           NA          NA\n5      NA           NA             NA             NA           NA          NA\n6      NA           NA             NA             NA           NA          NA\n  TEMPER_R PLAYWELL DISTRACTED HURTSAD CALMDOWN_R WAITFORTURN HARDWORK\n1       NA       NA         NA      NA         NA          NA       NA\n2       NA       NA         NA      NA         NA          NA       NA\n3       NA       NA         NA      NA         NA          NA       NA\n4       NA       NA         NA      NA         NA          NA       NA\n5       NA       NA         NA      NA         NA          NA       NA\n6       NA       NA         NA      NA         NA          NA       NA\n  SHARETOYS RECOGABC TALKABOUT WKTOSOLVE STRENGTHS HOPEFUL K10Q30 K10Q31\n1        NA       NA         2         2         2       2      4      4\n2        NA       NA         1         1         1       1      2      2\n3        NA       NA         1         1         2       1      2      2\n4        NA       NA         1         1         1       1      1      3\n5        NA       NA         1         1         1       1      2      4\n6        NA       NA         1         1         1       1      2      2\n  K10Q40_R GOFORHELP K10Q41_R K8Q31 K8Q32 K8Q34 HOWMUCH ATHOMEHC ARRANGEHC\n1        3         3        1     2     2     2       1        6         6\n2        1         2        2     1     1     3       4        6         6\n3        1         1        2     3     3     3       1        6         6\n4        1         1        2     1     1     2       1        6         6\n5        4         4        1     1     5     2       4        6         6\n6        2         3        4     1     1     2       1        6         6\n  K7Q02R_R K7Q04R_R PHYSACTIV HOURSLEEP05 HOURSLEEP OUTDOORSWKDAY OUTDOORSWKEND\n1        2        2         3          NA         3            NA            NA\n2        2        1         2          NA         5            NA            NA\n3        4        1         2          NA         5            NA            NA\n4        2        1         2          NA         5            NA            NA\n5        5        3         3          NA         5            NA            NA\n6        1        1         3          NA         4            NA            NA\n  SCREENTIME K6Q60_R K6Q61_R K8Q11 FOODSIT EVALFASD RECEVALFASD POSCHOICE\n1          4      NA      NA     1       1        2           2        NA\n2          5      NA      NA     2       1        2           2         1\n3          4      NA      NA     3       2        2           2         1\n4          4      NA      NA     4       1        2           2         1\n5          5      NA      NA     2       3        2           2        NA\n6          3      NA      NA     2       1        2           2         1\n  GAINSKILLS CHANGEAGE MISSMORTGAGE EVERHOMELESS K2Q35D HCABILITY HCEXTENT\n1         NA        NA            2            2     NA         2       NA\n2          1         1            2            2     NA         2       NA\n3          3         1            2            2     NA         1       NA\n4          3         2            2            2     NA         1       NA\n5         NA        NA            2            2     NA         1       NA\n6          3         3            2            2     NA         1       NA\n  K4Q20R DOCROOM WGTCONC GOWHENSICK DENTISTVISIT K4Q22_R TREATNEED K4Q24_R\n1      2       2       3         NA            3       3        NA       3\n2      3       1       3          1            2       3        NA       3\n3      2       3       3         NA            3       3        NA       3\n4     NA      NA       3          1            3       3        NA       3\n5     NA      NA       3         NA            2       3        NA       2\n6      1       2       3         NA            2       3        NA       3\n  K4Q26 C4Q04 HOSPITALER K4Q04_R K5Q11 K5Q20_R K5Q22 K5Q30 K5Q32 K5Q31_R K8Q21\n1    NA     1          1       1    NA       3    NA    NA    NA       2     1\n2    NA     2          1       3    NA       1     2     2     1       1     1\n3    NA     4          2       3    NA       1    NA     2    NA       3     1\n4    NA     1          1       1    NA      NA    NA    NA    NA      NA     1\n5     2     2          1       3    NA      NA    NA    NA    NA      NA     2\n6    NA     1          1       1    NA       3    NA    NA    NA       2     1\n  K8Q30 COUNTTO_R K7Q33 BEDTIME K3Q04_R ACE1 MAKEFRIEND STARTSCHOOL SUGARDRINK\n1     2        NA     1       3       1    3          1          NA         NA\n2     1        NA     2       1       1    2          1          NA         NA\n3     2        NA     1       2       1    1          1          NA         NA\n4     1        NA     3       2       1    1          1          NA         NA\n5     1        NA     1       2       1    1          3          NA         NA\n6     2        NA     3       1       1    1          2          NA         NA\n  VEGETABLES FRUIT PLANNEEDS_R RHYMEWORD_R GRADES HOMEEVIC YEAR CBSAFP_YN\n1         NA    NA          NA          NA      3        5 2023         1\n2         NA    NA          NA          NA      1        5 2023         1\n3         NA    NA          NA          NA      3        5 2023         1\n4         NA    NA          NA          NA      2        5 2023         1\n5         NA    NA          NA          NA      2        5 2023         1\n6         NA    NA          NA          NA      2        5 2023         1\n  METRO_YN MPC_YN TOTAGE_0_5 TOTAGE_6_11 TOTAGE_12_17 TOTCSHCN TOTNONSHCN\n1        1      1          0           1            0        1          0\n2        1      1          0           1            1        2          0\n3        1      1          0           0            1        0          1\n4        1      1          0           1            1        0          2\n5        1      1          0           1            1        1          1\n6        1      1          1           1            2        0          4\n  SC_CSHCN SC_RACE_R SC_HISPANIC_R SC_ENGLISH SC_K2Q10 SC_K2Q11 SC_K2Q12\n1        1         2             2          1        1        1        1\n2        1         1             1          1        2       NA       NA\n3        2         1             1          1        2       NA       NA\n4        2         1             1          1        2       NA       NA\n5        1         4             2          1        1        1        1\n6        2         1             1         NA        2       NA       NA\n  SC_K2Q13 SC_K2Q14 SC_K2Q15 SC_K2Q16 SC_K2Q17 SC_K2Q18 SC_K2Q19 SC_K2Q20\n1        2       NA       NA        2       NA       NA        2       NA\n2        1        1        1        2       NA       NA        2       NA\n3        2       NA       NA        2       NA       NA        2       NA\n4        2       NA       NA        2       NA       NA        2       NA\n5        1        1        1        2       NA       NA        2       NA\n6        2       NA       NA        2       NA       NA        2       NA\n  SC_K2Q21 SC_K2Q22 SC_K2Q23 SC_AGE_LT4 SC_AGE_LT6 SC_AGE_LT9 SC_AGE_LT10\n1       NA        2       NA          2          2          2           2\n2       NA        2       NA          2          2          2           2\n3       NA        2       NA          2          2          2           2\n4       NA        2       NA          2          2          2           2\n5       NA        2       NA          2          2          2           2\n6       NA        2       NA          2          2          2           2\n  AGEPOS4 TENURE_IF TOTMALE TOTFEMALE SC_RACE_R_IF SC_RACER SC_HISPANIC_R_IF\n1       1         0       1         0            0        2                0\n2       2         0       1         1            0        1                0\n3       1         0       0         1            0        1                0\n4       2         0       0         2            0        1                0\n5       3         0       0         2            0        3                0\n6       2         0       2         2            0        1                0\n  SC_SEX_IF BIRTHWT_OZ_S BREASTFEDEND_DAY_S BREASTFEDEND_WK_S BREASTFEDEND_MO_S\n1         0           96                 NA                NA                NA\n2         0          102                 NA                NA                NA\n3         0          112                 NA                NA                NA\n4         0          126                 NA                NA                NA\n5         0          103                 NA                NA                NA\n6         0          134                 NA                NA                NA\n  FRSTFORMULA_DAY_S FRSTFORMULA_WK_S FRSTFORMULA_MO_S FRSTSOLIDS_DAY_S\n1                NA               NA               NA               NA\n2                NA               NA               NA               NA\n3                NA               NA               NA               NA\n4                NA               NA               NA               NA\n5                NA               NA               NA               NA\n6                NA               NA               NA               NA\n  FRSTSOLIDS_WK_S FRSTSOLIDS_MO_S HOUSE_GEN FAMILY_R CURRINS INSGAP INSTYPE\n1              NA              NA         3        5       1      1       1\n2              NA              NA         2        1       1      1       2\n3              NA              NA         2        1       1      1       1\n4              NA              NA         2        1       1      1       2\n5              NA              NA         3        2       1      1       1\n6              NA              NA         2        1       1      1       1\n  BIRTHWT_VL BIRTHWT_L BIRTHWT FPL_IF A1_GRADE_IF BIRTH_YR_F SC_ASIAN SC_AIAN\n1          2         2       3      0           0          0        2       2\n2          2         2       3      0           0          0        2       2\n3          2         2       3      0           0          0        2       2\n4          2         2       3      0           0          0        2       2\n5          2         2       3      0           0          0        1       2\n6          2         2       3      0           0          0        2       2\n  SC_NHPI WEIGHT BMICLASS HHCOUNT_IF HIGRADE HIGRADE_TVIS FPL_I1 FPL_I2 FPL_I3\n1       2     NA       NA          0       3            3    266    266    266\n2       2  54.43        3          0       3            4    400    400    400\n3       2  57.15        2          0       2            2    190    190    190\n4       2  58.97        3          0       3            3    142    142    142\n5       2  42.18        2          0       2            2    101    101    101\n6       2  56.70        2          0       3            4    142    142    142\n  FPL_I4 FPL_I5 FPL_I6       FWC\n1    266    266    266 1318.4768\n2    400    400    400  978.4999\n3    190    190    190  904.1918\n4    142    142    142 1092.0973\n5    101    101    101  586.3879\n6    142    142    142 3474.3501\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(df_raw, BIRTHWT)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  BIRTHWT     n\n1       1   687\n2       2  3992\n3       3 48256\n4      NA  2227\n```\n\n\n:::\n:::\n\n\n# Data Cleaning/Prep\n\nSince we are only focusing on the variables listed above in the codebook I went ahead and selected them in the code chunk below while simultaneously renaming the columns to more easy-to-read names (see codebook).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create new dataframe with variables of interest\ndf <- df_raw |>\n  # Selects columns of interests and renames variables\n  select(\n    age = SC_AGE_YEARS,\n    sex = SC_SEX,\n    race = SC_RACE_R,\n    hispanic = SC_HISPANIC_R,\n    birth_weight_status = BIRTHWT,\n    birth_weight_very_low = BIRTHWT_VL,\n    birth_weight_low = BIRTHWT_L,\n    asthma = K2Q40A,\n    born_early = K2Q05,\n    breastfed = K6Q40,\n    poverty = FPL_I1,\n    education = HIGRADE_TVIS,\n    insurance_type = INSTYPE,\n    cigarettes = K9Q40,\n    smoke_inside = K9Q41,\n    vape = VAPE,\n    allergies = ALLERGIES)\n```\n:::\n\n\nNext I converted all the categorical variables into factors. First I selected all the column names that have Yes and No as responses and changed them all to factor with the levels 1,2 assigned to \"Yes\" and \"No\". For the remaining variables that were also factors I selected each column name individually and assigned their corresponding levels and labels according to the codebook provided by NCSH.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Converts categorical variables to factors, adds levels and labels\ndf <- df |>\n  mutate(across(c(\n    birth_weight_low, birth_weight_very_low, asthma, born_early,\n    breastfed, cigarettes, smoke_inside, vape, allergies, hispanic),\n    \\(x) factor(x, levels = c(1, 2), labels = c(\"Yes\", \"No\")))) |>\n  mutate(sex = factor(sex, \n                      levels = 1:2, \n                      labels = c(\"Male\", \"Female\"))) |>\n  mutate(race = factor(race, \n                       levels = c(1, 2, 3, 4, 5, 7), \n                       labels = c(\"White\", \n                                  \"Black or African American\", \n                                  \"American Indian or Alaska Native\", \n                                  \"Asian\", \n                                  \"Native Hawaiian and other Pacific Islander\", \n                                  \"Two or more races\"))) |> \n  #mutate(hispanic = factor(hispanic, \n  #                        levels = c(1, 2),\n  #                         labels = c(\"Hispanic or Latino origin\", \n  #                                    \"Not Hispanic or Latino origin\"))) |>\n  mutate(education = factor(education, \n                            levels = 1:4,\n                            labels = c(\"Less than high school\", \n                                       \"High school\", \n                                       \"Some college\", \n                                       \"College degree or higher\"))) |>\n  mutate(insurance_type = factor(insurance_type, \n                                levels = c(1, 2, 3, 5), \n                                labels = c(\"Public\", \"Private\", \n                                           \"Private and Public\", \n                                           \"Not insured\"))) |>\n  mutate(birth_weight_status = factor(birth_weight_status,\n                                      levels = 1:3,\n                                      labels = c(\n                                        \"Very low birth weight (less than 1,500g)\",\n                                        \"Low birth weight (less than 2,500g)\",\n                                        \"Not low birth weight\")\n                                      )\n         )\n```\n:::\n\n\nI ran a `str` function to make sure that all columns had the correct datatype and that they were assigned the correct labels and levels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check each column has the right data type and correct labels/levels\nstr(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t55162 obs. of  17 variables:\n $ age                  : num  11 14 17 12 10 14 15 12 8 13 ...\n $ sex                  : Factor w/ 2 levels \"Male\",\"Female\": 1 2 2 2 2 2 2 1 2 2 ...\n $ race                 : Factor w/ 6 levels \"White\",\"Black or African American\",..: 2 1 1 1 4 1 4 1 4 4 ...\n $ hispanic             : Factor w/ 2 levels \"Yes\",\"No\": 2 1 1 1 2 1 2 1 2 2 ...\n $ birth_weight_status  : Factor w/ 3 levels \"Very low birth weight (less than 1,500g)\",..: 3 3 3 3 3 3 3 3 NA NA ...\n $ birth_weight_very_low: Factor w/ 2 levels \"Yes\",\"No\": 2 2 2 2 2 2 2 2 NA NA ...\n $ birth_weight_low     : Factor w/ 2 levels \"Yes\",\"No\": 2 2 2 2 2 2 2 2 NA NA ...\n $ asthma               : Factor w/ 2 levels \"Yes\",\"No\": 1 2 2 2 2 2 2 2 2 2 ...\n $ born_early           : Factor w/ 2 levels \"Yes\",\"No\": 2 2 2 2 2 2 2 2 2 2 ...\n $ breastfed            : Factor w/ 2 levels \"Yes\",\"No\": NA NA NA NA NA NA NA NA NA NA ...\n $ poverty              : num  266 400 190 142 101 142 303 168 50 220 ...\n $ education            : Factor w/ 4 levels \"Less than high school\",..: 3 4 2 3 2 4 4 2 2 3 ...\n $ insurance_type       : Factor w/ 4 levels \"Public\",\"Private\",..: 1 2 1 2 1 1 2 1 NA NA ...\n $ cigarettes           : Factor w/ 2 levels \"Yes\",\"No\": 1 2 2 2 2 2 2 2 2 2 ...\n $ smoke_inside         : Factor w/ 2 levels \"Yes\",\"No\": NA NA NA NA NA NA NA NA NA NA ...\n $ vape                 : Factor w/ 2 levels \"Yes\",\"No\": 1 2 2 2 2 NA 2 2 2 2 ...\n $ allergies            : Factor w/ 2 levels \"Yes\",\"No\": 1 2 2 2 2 2 1 2 2 2 ...\n```\n\n\n:::\n:::\n\n\nFinally, to make sure that all recoding worked correctly I used the `summary` function to compare it's counts to the frequency tables provided by the NCSH.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Review the counts and check for NA's\nsummary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age            sex       \n Min.   : 0.00   Male  :28330  \n 1st Qu.: 4.00   Female:26832  \n Median : 8.00                 \n Mean   : 8.34                 \n 3rd Qu.:13.00                 \n Max.   :17.00                 \n                                         race       hispanic   \n White                                     :42095   Yes: 8170  \n Black or African American                 : 3686   No :46992  \n American Indian or Alaska Native          :  507              \n Asian                                     : 3632              \n Native Hawaiian and other Pacific Islander:  260              \n Two or more races                         : 4982              \n                               birth_weight_status birth_weight_very_low\n Very low birth weight (less than 1,500g):  687    Yes :  687           \n Low birth weight (less than 2,500g)     : 3992    No  :52248           \n Not low birth weight                    :48256    NA's: 2227           \n NA's                                    : 2227                         \n                                                                        \n                                                                        \n birth_weight_low  asthma      born_early   breastfed       poverty     \n Yes : 4679       Yes : 5209   Yes : 5897   Yes :18230   Min.   : 50.0  \n No  :48256       No  :49497   No  :48722   No  : 3108   1st Qu.:179.0  \n NA's: 2227       NA's:  456   NA's:  543   NA's:33824   Median :337.0  \n                                                         Mean   :287.3  \n                                                         3rd Qu.:400.0  \n                                                         Max.   :400.0  \n                    education                insurance_type  cigarettes  \n Less than high school   : 1342   Public            :11233   Yes : 5643  \n High school             : 6727   Private           :37966   No  :48417  \n Some college            :10895   Private and Public: 2659   NA's: 1102  \n College degree or higher:36198   Not insured       : 2299               \n                                  NA's              : 1005               \n                                                                         \n smoke_inside   vape       allergies   \n Yes :  616   Yes : 2576   Yes :15936  \n No  : 5000   No  :51531   No  :39079  \n NA's:49546   NA's: 1055   NA's:  147  \n                                       \n                                       \n                                       \n```\n\n\n:::\n:::\n\n\nBecause the `summary` function provides summary statistics for numerical/continuous variables I used the `count` function to match the frequency tables generated here and compared to the ones provided by NCSH.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Checking frequency of each individual age\ndf |>\n  count(age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   age    n\n1    0 1945\n2    1 2847\n3    2 4677\n4    3 4005\n5    4 3979\n6    5 4071\n7    6 2658\n8    7 2496\n9    8 2551\n10   9 2489\n11  10 2460\n12  11 2587\n13  12 2560\n14  13 2819\n15  14 2824\n16  15 3201\n17  16 3545\n18  17 3448\n```\n\n\n:::\n\n```{.r .cell-code}\n# Checking frequency of each poverty code\ndf |>\n  count(poverty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    poverty     n\n1        50  3421\n2        51    84\n3        52    42\n4        53    40\n5        54    54\n6        55    46\n7        56    52\n8        57    53\n9        58    46\n10       59    57\n11       60    64\n12       61    66\n13       62    47\n14       63    47\n15       64   100\n16       65    47\n17       66    56\n18       67    94\n19       68    71\n20       69    51\n21       70    65\n22       71    67\n23       72    80\n24       73    62\n25       74    66\n26       75    57\n27       76    73\n28       77    76\n29       78    54\n30       79    65\n31       80    45\n32       81   100\n33       82    51\n34       83    47\n35       84   125\n36       85   112\n37       86    81\n38       87    80\n39       88    63\n40       89    75\n41       90    66\n42       91    69\n43       92    71\n44       93    74\n45       94    82\n46       95    68\n47       96    59\n48       97    82\n49       98   136\n50       99    69\n51      100    92\n52      101   140\n53      102   109\n54      103    76\n55      104    87\n56      105    45\n57      106   102\n58      107    70\n59      108    86\n60      109    76\n61      110    88\n62      111    52\n63      112    97\n64      113    44\n65      114    93\n66      115   156\n67      116    51\n68      117    70\n69      118   106\n70      119    87\n71      120    54\n72      121   105\n73      122    43\n74      123    70\n75      124    82\n76      125    50\n77      126    67\n78      127   168\n79      128   118\n80      129   113\n81      130    82\n82      131    68\n83      132    59\n84      133    57\n85      134    70\n86      135   201\n87      136    90\n88      137    82\n89      138    51\n90      139    41\n91      140    96\n92      141    62\n93      142    69\n94      143   155\n95      144    83\n96      145    67\n97      146    73\n98      147    50\n99      148    75\n100     149   192\n101     150    52\n102     151    63\n103     152   118\n104     153   131\n105     154    71\n106     155    85\n107     156    39\n108     157    87\n109     158    64\n110     159    72\n111     160    40\n112     161   100\n113     162    95\n114     163    94\n115     164    61\n116     165    63\n117     166    98\n118     167    35\n119     168   278\n120     169    96\n121     170   201\n122     171    54\n123     172   158\n124     173    45\n125     174   124\n126     175    88\n127     176    64\n128     177    42\n129     178   109\n130     179   157\n131     180    51\n132     181    44\n133     182    97\n134     183    62\n135     184    59\n136     185   127\n137     186   125\n138     187    69\n139     188    39\n140     189    99\n141     190    83\n142     191   144\n143     192    77\n144     193    35\n145     194    60\n146     195    89\n147     196   109\n148     197    47\n149     198    48\n150     199   116\n151     200   162\n152     201    49\n153     202   294\n154     203    52\n155     204    81\n156     205    95\n157     206    70\n158     207    49\n159     208    44\n160     209   116\n161     210    33\n162     211    41\n163     212   335\n164     213    29\n165     214    57\n166     215   134\n167     216    45\n168     217   105\n169     218    41\n170     219   205\n171     220    42\n172     221    68\n173     222    68\n174     223   103\n175     224    65\n176     225    69\n177     226    48\n178     227    25\n179     228    92\n180     229   231\n181     230    92\n182     231    41\n183     232    60\n184     233   131\n185     234    28\n186     235    59\n187     236   292\n188     237    49\n189     238   129\n190     239    37\n191     240    25\n192     241    53\n193     242    53\n194     243   184\n195     244    96\n196     245    30\n197     246    83\n198     247    28\n199     248   134\n200     249    51\n201     250    39\n202     251    75\n203     252    48\n204     253   260\n205     254    70\n206     255   286\n207     256   144\n208     257    33\n209     258   160\n210     259    47\n211     260    39\n212     261   109\n213     262    30\n214     263   121\n215     264    33\n216     265    41\n217     266    46\n218     267    38\n219     268    42\n220     269    42\n221     270   379\n222     271    81\n223     272    75\n224     273    87\n225     274    35\n226     275    38\n227     276   220\n228     277    45\n229     278    51\n230     279    94\n231     280    69\n232     281    68\n233     282    31\n234     283    52\n235     284    46\n236     285    38\n237     286   418\n238     287    35\n239     288    42\n240     289    65\n241     290    47\n242     291    37\n243     292    33\n244     293   158\n245     294    33\n246     295    32\n247     296    23\n248     297   315\n249     298   113\n250     299    23\n251     300    46\n252     301    76\n253     302    33\n254     303   420\n255     304    37\n256     305    37\n257     306    73\n258     307   125\n259     308    26\n260     309    43\n261     310    81\n262     311    41\n263     312    31\n264     313    55\n265     314    44\n266     315   117\n267     316    31\n268     317    31\n269     318   218\n270     319    11\n271     320   147\n272     321    42\n273     322    34\n274     323   106\n275     324    19\n276     325    56\n277     326   158\n278     327    62\n279     328    28\n280     329    62\n281     330    61\n282     331    56\n283     332    72\n284     333    33\n285     334    24\n286     335    87\n287     336    33\n288     337   686\n289     338    48\n290     339    61\n291     340   349\n292     341    25\n293     342    33\n294     343    21\n295     344   238\n296     345    32\n297     346    27\n298     347    41\n299     348   116\n300     349    45\n301     350    40\n302     351    19\n303     352    59\n304     353    20\n305     354   124\n306     355    23\n307     356    19\n308     357    62\n309     358   117\n310     359    63\n311     360    20\n312     361   172\n313     362    23\n314     363    41\n315     364    69\n316     365    38\n317     366    28\n318     367    36\n319     368    20\n320     369    58\n321     370    15\n322     371   342\n323     372   138\n324     373    63\n325     374    54\n326     375    38\n327     376    15\n328     377    70\n329     378    50\n330     379    35\n331     381    45\n332     382   328\n333     383    16\n334     384   116\n335     385    27\n336     386    28\n337     387   161\n338     388    14\n339     389    33\n340     390    22\n341     391   154\n342     392    10\n343     393    21\n344     394    25\n345     395    32\n346     396    19\n347     397    55\n348     398    26\n349     399    33\n350     400 23317\n```\n\n\n:::\n:::\n\n\n## Missingness\n\nTwo variables stand out with missingness: `smoke_inside` and `breastfed`. This may be due to the structure of the survey that is visible in the codebook frequency list.\n\n`smoke_inside` has the two frequencies \"logical skip\" and \"no valid responses\" reported as `NA`s which is causing the `NA` count to increase.\n\n`breastfed` has the two frequencies \"Not in universe\" and \"No valid response\" both reporting as `NA`s which is also causing its `NA` count to increase.\n\nAs a group we decided to drop these two variables and only use `cigarettes` as our dichotomous variable that lists smoker status as Yes or No and doesn't have logical skips that bleed into the total `NA` count.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmiss_var_summary(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 17 × 3\n   variable              n_miss pct_miss\n   <chr>                  <int>    <num>\n 1 smoke_inside           49546   89.8  \n 2 breastfed              33824   61.3  \n 3 birth_weight_status     2227    4.04 \n 4 birth_weight_very_low   2227    4.04 \n 5 birth_weight_low        2227    4.04 \n 6 cigarettes              1102    2.00 \n 7 vape                    1055    1.91 \n 8 insurance_type          1005    1.82 \n 9 born_early               543    0.984\n10 asthma                   456    0.827\n11 allergies                147    0.266\n12 age                        0    0    \n13 sex                        0    0    \n14 race                       0    0    \n15 hispanic                   0    0    \n16 poverty                    0    0    \n17 education                  0    0    \n```\n\n\n:::\n:::\n\n\n### Dropping `smoke_inside` and `breastfed`\n\nWe decided to drop the variable `smoke_inside` as we felt that the variable `cigarettes` which represents household smoker status would better reflect the variable of interest and due to `smoke_inside` having 89.8% of missingness. `breastfed` was dropped due to a large amount of missingness `NA (61.3%)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Removes these variables\ndf <- df |> select(-c(smoke_inside, breastfed))\n\n# Check that those columns have been removed successfully\nnames(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"age\"                   \"sex\"                   \"race\"                 \n [4] \"hispanic\"              \"birth_weight_status\"   \"birth_weight_very_low\"\n [7] \"birth_weight_low\"      \"asthma\"                \"born_early\"           \n[10] \"poverty\"               \"education\"             \"insurance_type\"       \n[13] \"cigarettes\"            \"vape\"                  \"allergies\"            \n```\n\n\n:::\n:::\n\n\n# Creating the age category variable\n\nThe variables we decided to create are the age categories for the `age` variable. We chose to divide the ages into the following groups:\n\n- infants/toddlers = 0 to 2 years of age\n\n- preschool = 3 to 5 years of age\n\n- middle childhood = 5 to 12 years of age\n\n- teenagers = 13 to 17 years of age\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create age category (factor) variable\ndf <- df |>\n  mutate(\n    age_cats = case_when(\n      age < 3 ~ \"Infants/Toddlers (0-2)\",\n      age <= 5 ~ \"Preschool (3-5)\",\n      age <= 12 ~ \"Middle childhood (6-12)\",\n      TRUE ~ \"Teenagers (13-17)\"\n    ),\n    age_cats = factor(age_cats,\n                      levels = c(\"Infants/Toddlers (0-2)\", \n                                 \"Preschool (3-5)\", \n                                 \"Middle childhood (6-12)\", \n                                 \"Teenagers (13-17)\")),\n    .after = age\n  )\n\n# Ensure variable was created and that age matches selected category\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  age                age_cats    sex                      race hispanic\n1  11 Middle childhood (6-12)   Male Black or African American       No\n2  14       Teenagers (13-17) Female                     White      Yes\n3  17       Teenagers (13-17) Female                     White      Yes\n4  12 Middle childhood (6-12) Female                     White      Yes\n5  10 Middle childhood (6-12) Female                     Asian       No\n6  14       Teenagers (13-17) Female                     White      Yes\n   birth_weight_status birth_weight_very_low birth_weight_low asthma born_early\n1 Not low birth weight                    No               No    Yes         No\n2 Not low birth weight                    No               No     No         No\n3 Not low birth weight                    No               No     No         No\n4 Not low birth weight                    No               No     No         No\n5 Not low birth weight                    No               No     No         No\n6 Not low birth weight                    No               No     No         No\n  poverty                education insurance_type cigarettes vape allergies\n1     266             Some college         Public        Yes  Yes       Yes\n2     400 College degree or higher        Private         No   No        No\n3     190              High school         Public         No   No        No\n4     142             Some college        Private         No   No        No\n5     101              High school         Public         No   No        No\n6     142 College degree or higher         Public         No <NA>        No\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the categories are working correctly\ndf |>\n  group_by(age_cats) |>\n  summarise(min = min(age), max = max(age), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  age_cats                  min   max     n\n  <fct>                   <dbl> <dbl> <int>\n1 Infants/Toddlers (0-2)      0     2  9469\n2 Preschool (3-5)             3     5 12055\n3 Middle childhood (6-12)     6    12 17801\n4 Teenagers (13-17)          13    17 15837\n```\n\n\n:::\n:::\n\n\n# Labeling with `labelled`\n\nFor printing tables, I went ahead and created labels for each variable using the `labelled` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Assign labels to each variable\nvar_label(df) <- list(\n  age = \"Age, years\",\n  age_cats = \"Age group\",\n  sex = \"Sex\",\n  race = \"Race\",\n  hispanic = \"Hispanic or Latino origin\", \n  birth_weight_status = \"Birth weight Status\",\n  birth_weight_very_low = \"Very low birth weight (less than 1,500g)\",\n  birth_weight_low = \"Low birth weight (less than 2,500g)\",\n  asthma = \"Ever Asthma Diagnosis\",\n  born_early = \"Pre-term Birth (Born 3 or more weeks before due date)\",           \n  poverty = \"Familial poverty ratio\",\n  education = \"Highest level of education of adults\",\n  insurance_type = \"Insurance Type\",\n  cigarettes = \"Secondhand Smoking (Household smoker)\",\n  vape = \"Vaping exposure\",\n  allergies = \"Allergies\" \n)\n\n# Check variables labelled correctly\nvar_label(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$age\n[1] \"Age, years\"\n\n$age_cats\n[1] \"Age group\"\n\n$sex\n[1] \"Sex\"\n\n$race\n[1] \"Race\"\n\n$hispanic\n[1] \"Hispanic or Latino origin\"\n\n$birth_weight_status\n[1] \"Birth weight Status\"\n\n$birth_weight_very_low\n[1] \"Very low birth weight (less than 1,500g)\"\n\n$birth_weight_low\n[1] \"Low birth weight (less than 2,500g)\"\n\n$asthma\n[1] \"Ever Asthma Diagnosis\"\n\n$born_early\n[1] \"Pre-term Birth (Born 3 or more weeks before due date)\"\n\n$poverty\n[1] \"Familial poverty ratio\"\n\n$education\n[1] \"Highest level of education of adults\"\n\n$insurance_type\n[1] \"Insurance Type\"\n\n$cigarettes\n[1] \"Secondhand Smoking (Household smoker)\"\n\n$vape\n[1] \"Vaping exposure\"\n\n$allergies\n[1] \"Allergies\"\n```\n\n\n:::\n:::\n\n\n# Exporting cleaned file\n\nFinally, I saved the cleaned data file to use in the analysis notebook.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrio::export(df, here(\"data\", \"processed\", \"nsch2023_processed.rdata\"))\n```\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"01_epi690a_final_project_DM_files/libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"01_epi690a_final_project_DM_files/libs/jquery-1.11.3/jquery.min.js\"></script>\n<link href=\"01_epi690a_final_project_DM_files/libs/jquery-sparkline-2.1.2/jquery.sparkline.css\" rel=\"stylesheet\" />\n<script src=\"01_epi690a_final_project_DM_files/libs/jquery-sparkline-2.1.2/jquery.sparkline.js\"></script>\n<script src=\"01_epi690a_final_project_DM_files/libs/sparkline-binding-2.0/sparkline.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}